<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.36">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>R for Data Science (2e) - 13&nbsp; Joins</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./logicals.html" rel="next">
<link href="./tibble.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><script defer="" data-domain="r4ds.hadley.nz" src="https://plausible.io/js/plausible.js"></script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }"><div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Joins</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">R for Data Science (2e)</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/hadley/r4ds/" title="Source Code" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle sidebar-tool" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Welcome</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface-2e.html" class="sidebar-item-text sidebar-link">Preface to the second edition</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./whole-game.html" class="sidebar-item-text sidebar-link">Whole game</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-visualize.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data visualization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./workflow-basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Workflow: basics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-transform.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data transformation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./workflow-pipes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Workflow: Pipes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-tidy.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Data tidying</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./workflow-style.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Workflow: code style</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-import.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Data import</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./workflow-scripts.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Workflow: scripts and projects</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./EDA.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Exploratory Data Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./workflow-help.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Workflow: Getting help</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./transform.html" class="sidebar-item-text sidebar-link">Transform</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tibble.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Tibbles</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./joins.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Joins</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logicals.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Logical vectors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./numbers.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Numbers</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./strings.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Strings</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regexps.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Regular expressions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./factors.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Factors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datetimes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Dates and times</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./missing-values.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Missing values</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./column-wise.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Column-wise operations</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./wrangle.html" class="sidebar-item-text sidebar-link">Wrangle</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./parsing.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Parsing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./spreadsheets.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Spreadsheets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./databases.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Databases</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rectangling.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Data rectangling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./webscraping.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Web scraping</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./program.html" class="sidebar-item-text sidebar-link">Program</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./functions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./vectors.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Vectors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./iteration.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Iteration</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prog-strings.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Programming with strings</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./communicate.html" class="sidebar-item-text sidebar-link">Communicate</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rmarkdown.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">R Markdown</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./communicate-plots.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Graphics for communication</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rmarkdown-formats.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">R Markdown formats</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rmarkdown-workflow.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">R Markdown workflow</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><!-- margin-sidebar --><div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"> <span class="header-section-number">13.1</span> Introduction</a>
  <ul class="collapse">
<li><a href="#prerequisites" id="toc-prerequisites" class="nav-link" data-scroll-target="#prerequisites"> <span class="header-section-number">13.1.1</span> Prerequisites</a></li>
  </ul>
</li>
  <li>
<a href="#sec-nycflights13-relational" id="toc-sec-nycflights13-relational" class="nav-link" data-scroll-target="#sec-nycflights13-relational"> <span class="header-section-number">13.2</span> nycflights13</a>
  <ul class="collapse">
<li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"> <span class="header-section-number">13.2.1</span> Exercises</a></li>
  </ul>
</li>
  <li>
<a href="#keys" id="toc-keys" class="nav-link" data-scroll-target="#keys"> <span class="header-section-number">13.3</span> Keys</a>
  <ul class="collapse">
<li><a href="#exercises-1" id="toc-exercises-1" class="nav-link" data-scroll-target="#exercises-1"> <span class="header-section-number">13.3.1</span> Exercises</a></li>
  </ul>
</li>
  <li><a href="#sec-mutating-joins" id="toc-sec-mutating-joins" class="nav-link" data-scroll-target="#sec-mutating-joins"> <span class="header-section-number">13.4</span> Mutating joins</a></li>
  <li>
<a href="#join-types" id="toc-join-types" class="nav-link" data-scroll-target="#join-types"> <span class="header-section-number">13.5</span> Join types</a>
  <ul class="collapse">
<li><a href="#sec-inner-join" id="toc-sec-inner-join" class="nav-link" data-scroll-target="#sec-inner-join"> <span class="header-section-number">13.5.1</span> Inner join</a></li>
  <li><a href="#sec-outer-join" id="toc-sec-outer-join" class="nav-link" data-scroll-target="#sec-outer-join"> <span class="header-section-number">13.5.2</span> Outer joins</a></li>
  <li><a href="#sec-join-matches" id="toc-sec-join-matches" class="nav-link" data-scroll-target="#sec-join-matches"> <span class="header-section-number">13.5.3</span> Duplicate keys</a></li>
  <li><a href="#sec-join-by" id="toc-sec-join-by" class="nav-link" data-scroll-target="#sec-join-by"> <span class="header-section-number">13.5.4</span> Defining the key columns</a></li>
  <li><a href="#exercises-2" id="toc-exercises-2" class="nav-link" data-scroll-target="#exercises-2"> <span class="header-section-number">13.5.5</span> Exercises</a></li>
  </ul>
</li>
  <li><a href="#non-equi-joins" id="toc-non-equi-joins" class="nav-link" data-scroll-target="#non-equi-joins"> <span class="header-section-number">13.6</span> Non-equi joins</a></li>
  <li>
<a href="#sec-filtering-joins" id="toc-sec-filtering-joins" class="nav-link" data-scroll-target="#sec-filtering-joins"> <span class="header-section-number">13.7</span> Filtering joins</a>
  <ul class="collapse">
<li><a href="#exercises-3" id="toc-exercises-3" class="nav-link" data-scroll-target="#exercises-3"> <span class="header-section-number">13.7.1</span> Exercises</a></li>
  </ul>
</li>
  <li><a href="#join-problems" id="toc-join-problems" class="nav-link" data-scroll-target="#join-problems"> <span class="header-section-number">13.8</span> Join problems</a></li>
  </ul><div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/hadley/r4ds/edit/main/joins.qmd" class="toc-action">Edit this page</a></p><p><a href="https://github.com/hadley/r4ds/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-relational-data" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Joins</span></span></h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header><div class="status">
<p>You are reading the work-in-progress second edition of R for Data Science. This chapter is undergoing heavy restructuring and may be confusing or incomplete. You can find the complete first edition at <a href="https://r4ds.had.co.nz" class="uri">https://r4ds.had.co.nz</a>.</p>
</div>
<section id="introduction" class="level2" data-number="13.1"><h2 data-number="13.1" class="anchored" data-anchor-id="introduction">
<span class="header-section-number">13.1</span> Introduction</h2>
<p>Waiting on <a href="https://github.com/tidyverse/dplyr/pull/5910" class="uri">https://github.com/tidyverse/dplyr/pull/5910</a></p>
<!-- TODO: redraw all diagrams to match O'Reilly style -->
<p>It’s rare that a data analysis involves only a single data frame. Typically you have many data frames, and you must <strong>join</strong> them together to answer the questions that you’re interested in.</p>
<p>All the verbs in this chapter use a pair of data frames. Fortunately this is enough, since you can combine three data frames by combining two pairs. Sometimes both elements of a pair will be the same data frame. This is needed if, for example, you have a data frame of people, and each person has a reference to their parents.</p>
<p>There are two important types of joins. <strong>Mutating joins</strong> adds new variables to one data frame from matching observations in another. <strong>Filtering joins</strong>, which filters observations from one data frame based on whether or not they match an observation in another.</p>
<p>If you’re familiar with SQL, you should find these ideas very familiar as their instantiation in dplyr is very similar. We’ll point out any important differences as we go. Don’t worry if you’re not familiar with SQL, we’ll back to it in <a href="databases.html"><span>Chapter&nbsp;24</span></a>.</p>
<section id="prerequisites" class="level3" data-number="13.1.1"><h3 data-number="13.1.1" class="anchored" data-anchor-id="prerequisites">
<span class="header-section-number">13.1.1</span> Prerequisites</h3>
<p>We will explore relational data from nycflights13 using the join functions from dplyr.</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/hadley/nycflights13">nycflights13</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section></section><section id="sec-nycflights13-relational" class="level2" data-number="13.2"><h2 data-number="13.2" class="anchored" data-anchor-id="sec-nycflights13-relational">
<span class="header-section-number">13.2</span> nycflights13</h2>
<p>nycflights13 contains five tibbles : <code>airlines</code>, <code>airports</code>, <code>weather</code> and <code>planes</code> which are all related to the <code>flights</code> data frame that you used in <a href="data-transform.html"><span>Chapter&nbsp;4</span></a> on data transformation:</p>
<ul>
<li>
<p><code>airlines</code> lets you look up the full carrier name from its abbreviated code:</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">airlines</span></span>
<span><span class="co">#&gt; # A tibble: 16 × 2</span></span>
<span><span class="co">#&gt;   carrier name                    </span></span>
<span><span class="co">#&gt;   &lt;chr&gt;   &lt;chr&gt;                   </span></span>
<span><span class="co">#&gt; 1 9E      Endeavor Air Inc.       </span></span>
<span><span class="co">#&gt; 2 AA      American Airlines Inc.  </span></span>
<span><span class="co">#&gt; 3 AS      Alaska Airlines Inc.    </span></span>
<span><span class="co">#&gt; 4 B6      JetBlue Airways         </span></span>
<span><span class="co">#&gt; 5 DL      Delta Air Lines Inc.    </span></span>
<span><span class="co">#&gt; 6 EV      ExpressJet Airlines Inc.</span></span>
<span><span class="co">#&gt; # … with 10 more rows</span></span>
<span><span class="co">#&gt; # ℹ Use `print(n = ...)` to see more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</li>
<li>
<p><code>airports</code> gives information about each airport, identified by the <code>faa</code> airport code:</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">airports</span></span>
<span><span class="co">#&gt; # A tibble: 1,458 × 8</span></span>
<span><span class="co">#&gt;   faa   name                             lat   lon   alt    tz dst   tzone      </span></span>
<span><span class="co">#&gt;   &lt;chr&gt; &lt;chr&gt;                          &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;      </span></span>
<span><span class="co">#&gt; 1 04G   Lansdowne Airport               41.1 -80.6  1044    -5 A     America/Ne…</span></span>
<span><span class="co">#&gt; 2 06A   Moton Field Municipal Airport   32.5 -85.7   264    -6 A     America/Ch…</span></span>
<span><span class="co">#&gt; 3 06C   Schaumburg Regional             42.0 -88.1   801    -6 A     America/Ch…</span></span>
<span><span class="co">#&gt; 4 06N   Randall Airport                 41.4 -74.4   523    -5 A     America/Ne…</span></span>
<span><span class="co">#&gt; 5 09J   Jekyll Island Airport           31.1 -81.4    11    -5 A     America/Ne…</span></span>
<span><span class="co">#&gt; 6 0A9   Elizabethton Municipal Airport  36.4 -82.2  1593    -5 A     America/Ne…</span></span>
<span><span class="co">#&gt; # … with 1,452 more rows</span></span>
<span><span class="co">#&gt; # ℹ Use `print(n = ...)` to see more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</li>
<li>
<p><code>planes</code> gives information about each plane, identified by its <code>tailnum</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">planes</span></span>
<span><span class="co">#&gt; # A tibble: 3,322 × 9</span></span>
<span><span class="co">#&gt;   tailnum  year type                    manuf…¹ model engines seats speed engine</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;   &lt;int&gt; &lt;chr&gt;                   &lt;chr&gt;   &lt;chr&gt;   &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt; </span></span>
<span><span class="co">#&gt; 1 N10156   2004 Fixed wing multi engine EMBRAER EMB-…       2    55    NA Turbo…</span></span>
<span><span class="co">#&gt; 2 N102UW   1998 Fixed wing multi engine AIRBUS… A320…       2   182    NA Turbo…</span></span>
<span><span class="co">#&gt; 3 N103US   1999 Fixed wing multi engine AIRBUS… A320…       2   182    NA Turbo…</span></span>
<span><span class="co">#&gt; 4 N104UW   1999 Fixed wing multi engine AIRBUS… A320…       2   182    NA Turbo…</span></span>
<span><span class="co">#&gt; 5 N10575   2002 Fixed wing multi engine EMBRAER EMB-…       2    55    NA Turbo…</span></span>
<span><span class="co">#&gt; 6 N105UW   1999 Fixed wing multi engine AIRBUS… A320…       2   182    NA Turbo…</span></span>
<span><span class="co">#&gt; # … with 3,316 more rows, and abbreviated variable name ¹​manufacturer</span></span>
<span><span class="co">#&gt; # ℹ Use `print(n = ...)` to see more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</li>
<li>
<p><code>weather</code> gives the weather at each NYC airport for each hour:</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">weather</span></span>
<span><span class="co">#&gt; # A tibble: 26,115 × 15</span></span>
<span><span class="co">#&gt;   origin  year month   day  hour  temp  dewp humid wind_dir wind_speed wind_gust</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;  &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;    &lt;dbl&gt;      &lt;dbl&gt;     &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 EWR     2013     1     1     1  39.0  26.1  59.4      270      10.4         NA</span></span>
<span><span class="co">#&gt; 2 EWR     2013     1     1     2  39.0  27.0  61.6      250       8.06        NA</span></span>
<span><span class="co">#&gt; 3 EWR     2013     1     1     3  39.0  28.0  64.4      240      11.5         NA</span></span>
<span><span class="co">#&gt; 4 EWR     2013     1     1     4  39.9  28.0  62.2      250      12.7         NA</span></span>
<span><span class="co">#&gt; 5 EWR     2013     1     1     5  39.0  28.0  64.4      260      12.7         NA</span></span>
<span><span class="co">#&gt; 6 EWR     2013     1     1     6  37.9  28.0  67.2      240      11.5         NA</span></span>
<span><span class="co">#&gt; # … with 26,109 more rows, and 4 more variables: precip &lt;dbl&gt;, pressure &lt;dbl&gt;,</span></span>
<span><span class="co">#&gt; #   visib &lt;dbl&gt;, time_hour &lt;dttm&gt;</span></span>
<span><span class="co">#&gt; # ℹ Use `print(n = ...)` to see more rows, and `colnames()` to see all variable names</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</li>
</ul>
<p>These datasets are connected as follows:</p>
<ul>
<li><p><code>flights</code> connects to <code>planes</code> via a single variable, <code>tailnum</code>.</p></li>
<li><p><code>flights</code> connects to <code>airlines</code> through the <code>carrier</code> variable.</p></li>
<li><p><code>flights</code> connects to <code>airports</code> in two ways: via the <code>origin</code> and <code>dest</code> variables.</p></li>
<li><p><code>flights</code> connects to <code>weather</code> via <code>origin</code> (the location), and <code>year</code>, <code>month</code>, <code>day</code> and <code>hour</code> (the time).</p></li>
</ul>
<p>One way to show the relationships between the different data frames is with a diagram, as in <a href="#fig-flights-relationships">Figure&nbsp;<span>13.1</span></a>. This diagram is a little overwhelming, but it’s simple compared to some you’ll see in the wild! The key to understanding diagrams like this is that you’ll solve real problems by working with pairs of data frames. You don’t need to understand the whole thing; you just need to understand the chain of connections between the two data frames that you’re interested in.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-flights-relationships" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="diagrams/relational-nycflights.png" class="img-fluid figure-img" alt="Diagram showing the relationships between airports, planes, flights, weather, and airlines datasets from the nycflights13 package. The faa variable in the airports data frame is connected to the origin and dest variables in the flights data frame. The tailnum variable in the planes data frame is connected to the tailnum variable in flights. The year, month, day, hour, and origin variables are connected to the variables with the same name in the flights data frame. And finally the carrier variables in the airlines data frame is connected to the carrier variable in the flights data frame. There are no direct connections between airports, planes, airlines, and weather data frames." width="396"></p>
<p></p><figcaption class="figure-caption">Figure 13.1: Connections between all six data frames in the nycflights package.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<section id="exercises" class="level3" data-number="13.2.1"><h3 data-number="13.2.1" class="anchored" data-anchor-id="exercises">
<span class="header-section-number">13.2.1</span> Exercises</h3>
<ol type="1">
<li><p>Imagine you wanted to draw (approximately) the route each plane flies from its origin to its destination. What variables would you need? What data frames would you need to combine?</p></li>
<li><p>We forgot to draw the relationship between <code>weather</code> and <code>airports</code>. What is the relationship and how should it appear in the diagram?</p></li>
<li><p><code>weather</code> only contains information for the origin (NYC) airports. If it contained weather records for all airports in the USA, what additional relation would it define with <code>flights</code>?</p></li>
</ol></section></section><section id="keys" class="level2" data-number="13.3"><h2 data-number="13.3" class="anchored" data-anchor-id="keys">
<span class="header-section-number">13.3</span> Keys</h2>
<p>The variables used to connect each pair of data frames are called <strong>keys</strong>. A key is a variable (or set of variables) that uniquely identifies an observation. In simple cases, a single variable is sufficient to identify an observation. For example, each plane is uniquely identified by its <code>tailnum</code>. In other cases, multiple variables may be needed. For example, to identify an observation in <code>weather</code> you need five variables: <code>year</code>, <code>month</code>, <code>day</code>, <code>hour</code>, and <code>origin</code>.</p>
<p>There are two types of keys:</p>
<ul>
<li><p>A <strong>primary key</strong> uniquely identifies an observation in its own data frame. For example, <code>planes$tailnum</code> is a primary key because it uniquely identifies each plane in the <code>planes</code> data frame.</p></li>
<li><p>A <strong>foreign key</strong> uniquely identifies an observation in another data frame. For example, <code>flights$tailnum</code> is a foreign key because it appears in the <code>flights</code> data frame where it matches each flight to a unique plane.</p></li>
</ul>
<p>A variable can be both a primary key <em>and</em> a foreign key. For example, <code>origin</code> is part of the <code>weather</code> primary key, and is also a foreign key for the <code>airports</code> data frame.</p>
<p>Once you’ve identified the primary keys in your data frames, it’s good practice to verify that they do indeed uniquely identify each observation. One way to do that is to <code><a href="https://dplyr.tidyverse.org/reference/count.html">count()</a></code> the primary keys and look for entries where <code>n</code> is greater than one:</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">planes</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">tailnum</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">n</span> <span class="op">&gt;</span> <span class="fl">1</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 0 × 2</span></span>
<span><span class="co">#&gt; # … with 2 variables: tailnum &lt;chr&gt;, n &lt;int&gt;</span></span>
<span><span class="co">#&gt; # ℹ Use `colnames()` to see all variable names</span></span>
<span></span>
<span><span class="va">weather</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">year</span>, <span class="va">month</span>, <span class="va">day</span>, <span class="va">hour</span>, <span class="va">origin</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">n</span> <span class="op">&gt;</span> <span class="fl">1</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 3 × 6</span></span>
<span><span class="co">#&gt;    year month   day  hour origin     n</span></span>
<span><span class="co">#&gt;   &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt;  &lt;int&gt;</span></span>
<span><span class="co">#&gt; 1  2013    11     3     1 EWR        2</span></span>
<span><span class="co">#&gt; 2  2013    11     3     1 JFK        2</span></span>
<span><span class="co">#&gt; 3  2013    11     3     1 LGA        2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Sometimes a data frame doesn’t have an explicit primary key: each row is an observation, but no combination of variables reliably identifies it. For example, what’s the primary key in the <code>flights</code> data frame? You might think it would be the date plus the flight or tail number, but neither of those are unique:</p>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">flights</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">year</span>, <span class="va">month</span>, <span class="va">day</span>, <span class="va">flight</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">n</span> <span class="op">&gt;</span> <span class="fl">1</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 29,768 × 5</span></span>
<span><span class="co">#&gt;    year month   day flight     n</span></span>
<span><span class="co">#&gt;   &lt;int&gt; &lt;int&gt; &lt;int&gt;  &lt;int&gt; &lt;int&gt;</span></span>
<span><span class="co">#&gt; 1  2013     1     1      1     2</span></span>
<span><span class="co">#&gt; 2  2013     1     1      3     2</span></span>
<span><span class="co">#&gt; 3  2013     1     1      4     2</span></span>
<span><span class="co">#&gt; 4  2013     1     1     11     3</span></span>
<span><span class="co">#&gt; 5  2013     1     1     15     2</span></span>
<span><span class="co">#&gt; 6  2013     1     1     21     2</span></span>
<span><span class="co">#&gt; # … with 29,762 more rows</span></span>
<span><span class="co">#&gt; # ℹ Use `print(n = ...)` to see more rows</span></span>
<span></span>
<span><span class="va">flights</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">year</span>, <span class="va">month</span>, <span class="va">day</span>, <span class="va">tailnum</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">n</span> <span class="op">&gt;</span> <span class="fl">1</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 64,928 × 5</span></span>
<span><span class="co">#&gt;    year month   day tailnum     n</span></span>
<span><span class="co">#&gt;   &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;chr&gt;   &lt;int&gt;</span></span>
<span><span class="co">#&gt; 1  2013     1     1 N0EGMQ      2</span></span>
<span><span class="co">#&gt; 2  2013     1     1 N11189      2</span></span>
<span><span class="co">#&gt; 3  2013     1     1 N11536      2</span></span>
<span><span class="co">#&gt; 4  2013     1     1 N11544      3</span></span>
<span><span class="co">#&gt; 5  2013     1     1 N11551      2</span></span>
<span><span class="co">#&gt; 6  2013     1     1 N12540      2</span></span>
<span><span class="co">#&gt; # … with 64,922 more rows</span></span>
<span><span class="co">#&gt; # ℹ Use `print(n = ...)` to see more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>When starting to work with this data, we had naively assumed that each flight number would be only used once per day: that would make it much easier to communicate problems with a specific flight. Unfortunately that is not the case! If a data frame lacks a primary key, it’s sometimes useful to add one with <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> and <code><a href="https://dplyr.tidyverse.org/reference/ranking.html">row_number()</a></code>. That makes it easier to match observations if you’ve done some filtering and want to check back in with the original data. This is called a <strong>surrogate key</strong>.</p>
<p>A primary key and the corresponding foreign key in another data frame form a <strong>relation</strong>. Relations are typically one-to-many. For example, each flight has one plane, but each plane has many flights. In other data, you’ll occasionally see a 1-to-1 relationship. You can think of this as a special case of 1-to-many. You can model many-to-many relations with a many-to-1 relation plus a 1-to-many relation. For example, in this data there’s a many-to-many relationship between airlines and airports: each airline flies to many airports; each airport hosts many airlines.</p>
<section id="exercises-1" class="level3" data-number="13.3.1"><h3 data-number="13.3.1" class="anchored" data-anchor-id="exercises-1">
<span class="header-section-number">13.3.1</span> Exercises</h3>
<ol type="1">
<li><p>Add a surrogate key to <code>flights</code>.</p></li>
<li><p>We know that some days of the year are “special”, and fewer people than usual fly on them. How might you represent that data as a data frame? What would be the primary keys of that data frame? How would it connect to the existing data frames?</p></li>
<li>
<p>Identify the keys in the following datasets</p>
<ol type="a">
<li><code><a href="https://rdrr.io/pkg/Lahman/man/Batting.html">Lahman::Batting</a></code></li>
<li><code><a href="https://rdrr.io/pkg/babynames/man/babynames.html">babynames::babynames</a></code></li>
<li><code>nasaweather::atmos</code></li>
<li><code>fueleconomy::vehicles</code></li>
<li><code><a href="https://ggplot2.tidyverse.org/reference/diamonds.html">ggplot2::diamonds</a></code></li>
</ol>
<p>(You might need to install some packages and read some documentation.)</p>
</li>
<li>
<p>Draw a diagram illustrating the connections between the <code>Batting</code>, <code>People</code>, and <code>Salaries</code> data frames in the Lahman package. Draw another diagram that shows the relationship between <code>People</code>, <code>Managers</code>, <code>AwardsManagers</code>.</p>
<p>How would you characterise the relationship between the <code>Batting</code>, <code>Pitching</code>, and <code>Fielding</code> data frames?</p>
</li>
</ol></section></section><section id="sec-mutating-joins" class="level2" data-number="13.4"><h2 data-number="13.4" class="anchored" data-anchor-id="sec-mutating-joins">
<span class="header-section-number">13.4</span> Mutating joins</h2>
<p>The first tool we’ll look at for combining a pair of data frames is the <strong>mutating join</strong>. A mutating join allows you to combine variables from two data frames. It first matches observations by their keys, then copies across variables from one data frame to the other.</p>
<p>Like <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code>, the join functions add variables to the right, so if you have a lot of variables already, the new variables won’t get printed out. For these examples, we’ll make it easier to see what’s going on in the examples by creating a narrower dataset:</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">flights2</span> <span class="op">&lt;-</span> <span class="va">flights</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">year</span><span class="op">:</span><span class="va">day</span>, <span class="va">hour</span>, <span class="va">origin</span>, <span class="va">dest</span>, <span class="va">tailnum</span>, <span class="va">carrier</span><span class="op">)</span></span>
<span><span class="va">flights2</span></span>
<span><span class="co">#&gt; # A tibble: 336,776 × 8</span></span>
<span><span class="co">#&gt;    year month   day  hour origin dest  tailnum carrier</span></span>
<span><span class="co">#&gt;   &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;  </span></span>
<span><span class="co">#&gt; 1  2013     1     1     5 EWR    IAH   N14228  UA     </span></span>
<span><span class="co">#&gt; 2  2013     1     1     5 LGA    IAH   N24211  UA     </span></span>
<span><span class="co">#&gt; 3  2013     1     1     5 JFK    MIA   N619AA  AA     </span></span>
<span><span class="co">#&gt; 4  2013     1     1     5 JFK    BQN   N804JB  B6     </span></span>
<span><span class="co">#&gt; 5  2013     1     1     6 LGA    ATL   N668DN  DL     </span></span>
<span><span class="co">#&gt; 6  2013     1     1     5 EWR    ORD   N39463  UA     </span></span>
<span><span class="co">#&gt; # … with 336,770 more rows</span></span>
<span><span class="co">#&gt; # ℹ Use `print(n = ...)` to see more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>(Remember, when you’re in RStudio, you can also use <code><a href="https://rdrr.io/r/utils/View.html">View()</a></code> to avoid this problem.)</p>
<p>Imagine you want to add the full airline name to the <code>flights2</code> data. You can combine the <code>airlines</code> and <code>flights2</code> data frames with <code><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join()</a></code>:</p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">flights2</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="op">!</span><span class="va">origin</span>, <span class="op">!</span><span class="va">dest</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">airlines</span>, by <span class="op">=</span> <span class="st">"carrier"</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 336,776 × 9</span></span>
<span><span class="co">#&gt;    year month   day  hour dest  tailnum carrier origin name                  </span></span>
<span><span class="co">#&gt;   &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;                 </span></span>
<span><span class="co">#&gt; 1  2013     1     1     5 IAH   N14228  UA      EWR    United Air Lines Inc. </span></span>
<span><span class="co">#&gt; 2  2013     1     1     5 IAH   N24211  UA      LGA    United Air Lines Inc. </span></span>
<span><span class="co">#&gt; 3  2013     1     1     5 MIA   N619AA  AA      JFK    American Airlines Inc.</span></span>
<span><span class="co">#&gt; 4  2013     1     1     5 BQN   N804JB  B6      JFK    JetBlue Airways       </span></span>
<span><span class="co">#&gt; 5  2013     1     1     6 ATL   N668DN  DL      LGA    Delta Air Lines Inc.  </span></span>
<span><span class="co">#&gt; 6  2013     1     1     5 ORD   N39463  UA      EWR    United Air Lines Inc. </span></span>
<span><span class="co">#&gt; # … with 336,770 more rows</span></span>
<span><span class="co">#&gt; # ℹ Use `print(n = ...)` to see more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The result of joining airlines to flights2 is an additional variable: <code>name</code>. This is why we call this type of join a mutating join. In this case, you could get the same result using <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> and a pair of base R functions, <code>[</code> and <code><a href="https://rdrr.io/r/base/match.html">match()</a></code>:</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">flights2</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="op">!</span><span class="va">origin</span>, <span class="op">!</span><span class="va">dest</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span></span>
<span>    name <span class="op">=</span> <span class="va">airlines</span><span class="op">$</span><span class="va">name</span><span class="op">[</span><span class="fu"><a href="https://rdrr.io/r/base/match.html">match</a></span><span class="op">(</span><span class="va">carrier</span>, <span class="va">airlines</span><span class="op">$</span><span class="va">carrier</span><span class="op">)</span><span class="op">]</span></span>
<span>  <span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 336,776 × 9</span></span>
<span><span class="co">#&gt;    year month   day  hour dest  tailnum carrier origin name                  </span></span>
<span><span class="co">#&gt;   &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;  &lt;chr&gt;                 </span></span>
<span><span class="co">#&gt; 1  2013     1     1     5 IAH   N14228  UA      EWR    United Air Lines Inc. </span></span>
<span><span class="co">#&gt; 2  2013     1     1     5 IAH   N24211  UA      LGA    United Air Lines Inc. </span></span>
<span><span class="co">#&gt; 3  2013     1     1     5 MIA   N619AA  AA      JFK    American Airlines Inc.</span></span>
<span><span class="co">#&gt; 4  2013     1     1     5 BQN   N804JB  B6      JFK    JetBlue Airways       </span></span>
<span><span class="co">#&gt; 5  2013     1     1     6 ATL   N668DN  DL      LGA    Delta Air Lines Inc.  </span></span>
<span><span class="co">#&gt; 6  2013     1     1     5 ORD   N39463  UA      EWR    United Air Lines Inc. </span></span>
<span><span class="co">#&gt; # … with 336,770 more rows</span></span>
<span><span class="co">#&gt; # ℹ Use `print(n = ...)` to see more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>But this is hard to generalize when you need to match multiple variables, and takes close reading to figure out the overall intent.</p>
<p>The following sections explain, in detail, how mutating joins work. You’ll start by learning a useful visual representation of joins. We’ll then use that to explain the four mutating join functions: the inner join, and the three outer joins. When working with real data, keys don’t always uniquely identify observations, so next we’ll talk about what happens when there isn’t a unique match. Finally, you’ll learn how to tell dplyr which variables are the keys for a given join.</p>
</section><section id="join-types" class="level2" data-number="13.5"><h2 data-number="13.5" class="anchored" data-anchor-id="join-types">
<span class="header-section-number">13.5</span> Join types</h2>
<p>To help you learn how joins work, we’ll use a visual representation:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="diagrams/join-setup.png" class="img-fluid" alt="x and y are two data frames with 2 columns and 3 rows each. The first column in each is the key and the second is the value. The contents of these data frames are given in the subsequent code chunk." width="118"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">x</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tribble.html">tribble</a></span><span class="op">(</span></span>
<span>  <span class="op">~</span><span class="va">key</span>, <span class="op">~</span><span class="va">val_x</span>,</span>
<span>     <span class="fl">1</span>, <span class="st">"x1"</span>,</span>
<span>     <span class="fl">2</span>, <span class="st">"x2"</span>,</span>
<span>     <span class="fl">3</span>, <span class="st">"x3"</span></span>
<span><span class="op">)</span></span>
<span><span class="va">y</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tribble.html">tribble</a></span><span class="op">(</span></span>
<span>  <span class="op">~</span><span class="va">key</span>, <span class="op">~</span><span class="va">val_y</span>,</span>
<span>     <span class="fl">1</span>, <span class="st">"y1"</span>,</span>
<span>     <span class="fl">2</span>, <span class="st">"y2"</span>,</span>
<span>     <span class="fl">4</span>, <span class="st">"y3"</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The coloured column represents the “key” variable: these are used to match the rows between the data frames. The grey column represents the “value” column that is carried along for the ride. In these examples we’ve shown a single key variable, but the idea generalises in a straightforward way to multiple keys and multiple values.</p>
<p>A join is a way of connecting each row in <code>x</code> to zero, one, or more rows in <code>y</code>. The following diagram shows each potential match as an intersection of a pair of lines.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="diagrams/join-setup2.png" class="img-fluid" alt="x and y data frames placed next to each other. with the key variable moved up front in y so that the key variable in x and key variable in y appear next to each other." width="166"></p>
</div>
</div>
<p>If you look closely, you’ll notice that we’ve switched the order of the key and value columns in <code>x</code>. This is to emphasize that joins match based on the key; the other columns are just carried along for the ride.</p>
<p>In an actual join, matches will be indicated with dots. The number of dots = the number of matches = the number of rows in the output.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="diagrams/join-inner.png" class="img-fluid" alt="Keys 1 and 2 in x and y data frames are matched and indicated with lines joining these rows with dot in the middle. Hence, there are two dots in this diagram. The resulting joined data frame has two rows and 3 columns: key, val_x, and val_y. Values in the key column are 1 and 2, the matched values." width="338"></p>
</div>
</div>
<section id="sec-inner-join" class="level3" data-number="13.5.1"><h3 data-number="13.5.1" class="anchored" data-anchor-id="sec-inner-join">
<span class="header-section-number">13.5.1</span> Inner join</h3>
<p>The simplest type of join is the <strong>inner join</strong>. An inner join matches pairs of observations whenever their keys are equal:</p>
<div class="cell" data-opts.label="true">
<div class="cell-output-display">
<p><img src="diagrams/join-inner.png" class="img-fluid" alt="Keys 1 and 2 in x and y data frames are matched and indicated with lines joining these rows with dot in the middle. Hence, there are two dots in this diagram. The resulting joined data frame has two rows and 3 columns: key, val_x, and val_y. Values in the key column are 1 and 2, the matched values." width="338"></p>
</div>
</div>
<p>(To be precise, this is an inner <strong>equijoin</strong> because the keys are matched using the equality operator. Since most joins are equijoins we usually drop that specification.)</p>
<p>The output of an inner join is a new data frame that contains the key, the x values, and the y values. We use <code>by</code> to tell dplyr which variable is the key:</p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">x</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">inner_join</a></span><span class="op">(</span><span class="va">y</span>, by <span class="op">=</span> <span class="st">"key"</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 2 × 3</span></span>
<span><span class="co">#&gt;     key val_x val_y</span></span>
<span><span class="co">#&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;</span></span>
<span><span class="co">#&gt; 1     1 x1    y1   </span></span>
<span><span class="co">#&gt; 2     2 x2    y2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The most important property of an inner join is that unmatched rows are not included in the result. This means that generally inner joins are usually not appropriate for use in analysis because it’s too easy to lose observations.</p>
</section><section id="sec-outer-join" class="level3" data-number="13.5.2"><h3 data-number="13.5.2" class="anchored" data-anchor-id="sec-outer-join">
<span class="header-section-number">13.5.2</span> Outer joins</h3>
<p>An inner join keeps observations that appear in both data frames. An <strong>outer join</strong> keeps observations that appear in at least one of the data frames. There are three types of outer joins:</p>
<ul>
<li>A <strong>left join</strong> keeps all observations in <code>x</code>.</li>
<li>A <strong>right join</strong> keeps all observations in <code>y</code>.</li>
<li>A <strong>full join</strong> keeps all observations in <code>x</code> and <code>y</code>.</li>
</ul>
<p>These joins work by adding an additional “virtual” observation to each data frame. This observation has a key that always matches (if no other key matches), and a value filled with <code>NA</code>.</p>
<p>Graphically, that looks like:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="diagrams/join-outer.png" class="img-fluid" alt="Three diagrams for left, right, and full joins. In each diagram data frame x is on the left and y is on the right. The result of the join is always a data frame with three columns (key, val_x, and val_y). Left join: keys 1 and 2 from x are matched to those in y, key 3 is also carried along to the joined result since it's on the left data frame, but key 4 from y is not carried along since it's on the right but not on the left. The result is a data frame with 3 rows: keys 1, 2, and 3, all values from val_x, and the corresponding values from val_y for keys 1 and 2 with an NA for key 3, val_y. Right join: keys 1 and 2 from x are matched to those in y, key 4 is also carried along to the joined result since it's on the right data frame, but key 3 from x is not carried along since it's on the left but not on the right. The result is a data frame with 3 rows: keys 1, 2, and 4, all values from val_y, and the corresponding values from val_x for keys 1 and 2 with an NA for key 4, val_x. Full join: The resulting data frame has 4 rows: keys 1, 2, 3, and 4 with all values from val_x and val_y, however key 2, val_y and key 4, val_x are NAs since those keys aren't present in their respective data frames." width="355"></p>
</div>
</div>
<p>The most commonly used join is the left join: you use this whenever you look up additional data from another data frame, because it preserves the original observations even when there isn’t a match. The left join should be your default join: use it unless you have a strong reason to prefer one of the others.</p>
<p>Another way to depict the different types of joins is with a Venn diagram:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="diagrams/join-venn.png" class="img-fluid" alt="Venn diagrams for inner, full, left, and right joins. Each join represented with two intersecting circles representing data frames x and y, with x on the right and y on the left. Shading indicates the result of the join. Inner join: Only intersection is shaded. Full join: Everything is shaded. Left join: Only x is shaded, but not the area in y that doesn't intersect with x. Right join: Only y is shaded, but not the area in x that doesn't intersect with y." width="551"></p>
</div>
</div>
<p>However, this is not a great representation. It might jog your memory about which join preserves the observations in which data frame, but it suffers from a major limitation: a Venn diagram can’t show what happens when keys don’t uniquely identify an observation.</p>
</section><section id="sec-join-matches" class="level3" data-number="13.5.3"><h3 data-number="13.5.3" class="anchored" data-anchor-id="sec-join-matches">
<span class="header-section-number">13.5.3</span> Duplicate keys</h3>
<p>So far all the diagrams have assumed that the keys are unique. But that’s not always the case. This section explains what happens when the keys are not unique. There are two possibilities:</p>
<p>TODO: update for new warnings</p>
<ol type="1">
<li>
<p>One data frame has duplicate keys. This is useful when you want to add in additional information as there is typically a one-to-many relationship.</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="diagrams/join-one-to-many.png" class="img-fluid" alt="Diagram describing a left join where one of the data frames (x) has duplicate keys. Data frame x is on the left, has 4 rows and 2 columns (key, val_x), and has the keys 1, 2, 2, and 1. Data frame y is on the right, has 2 rows and 2 columns (key, val_y), and has the keys 1 and 2. Left joining these two data frames yields a data frame with 4 rows (keys 1, 2, 2, and 1) and 3 columns (val_x, key, val_y). All values from x$val_x are carried along, values in y for key 1 and 2 are duplicated." width="279"></p>
</div>
</div>
<p>Note that we’ve put the key column in a slightly different position in the output. This reflects that the key is a primary key in <code>y</code> and a foreign key in <code>x</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">x</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tribble.html">tribble</a></span><span class="op">(</span></span>
<span>  <span class="op">~</span><span class="va">key</span>, <span class="op">~</span><span class="va">val_x</span>,</span>
<span>     <span class="fl">1</span>, <span class="st">"x1"</span>,</span>
<span>     <span class="fl">2</span>, <span class="st">"x2"</span>,</span>
<span>     <span class="fl">2</span>, <span class="st">"x3"</span>,</span>
<span>     <span class="fl">1</span>, <span class="st">"x4"</span></span>
<span><span class="op">)</span></span>
<span><span class="va">y</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tribble.html">tribble</a></span><span class="op">(</span></span>
<span>  <span class="op">~</span><span class="va">key</span>, <span class="op">~</span><span class="va">val_y</span>,</span>
<span>     <span class="fl">1</span>, <span class="st">"y1"</span>,</span>
<span>     <span class="fl">2</span>, <span class="st">"y2"</span></span>
<span><span class="op">)</span></span>
<span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">y</span>, by <span class="op">=</span> <span class="st">"key"</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 4 × 3</span></span>
<span><span class="co">#&gt;     key val_x val_y</span></span>
<span><span class="co">#&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;</span></span>
<span><span class="co">#&gt; 1     1 x1    y1   </span></span>
<span><span class="co">#&gt; 2     2 x2    y2   </span></span>
<span><span class="co">#&gt; 3     2 x3    y2   </span></span>
<span><span class="co">#&gt; 4     1 x4    y1</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</li>
<li>
<p>Both data frames have duplicate keys. This is usually an error because in neither data frame do the keys uniquely identify an observation. When you join duplicated keys, you get all possible combinations, the Cartesian product:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="diagrams/join-many-to-many.png" class="img-fluid" alt="Diagram describing a left join where both data frames (x and y) have duplicate keys. Data frame x is on the left, has 4 rows and 2 columns (key, val_x), and has the keys 1, 2, 2, and 3. Data frame y is on the right, has 4 rows and 2 columns (key, val_y), and has the keys 1, 2, 2, and 3 as well. Left joining these two data frames yields a data frame with 6 rows (keys 1, 2, 2, 2, 2, and 3) and 3 columns (key, val_x, val_y). All values from both datasets are included." width="342"></p>
</div>
</div>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">x</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tribble.html">tribble</a></span><span class="op">(</span></span>
<span>  <span class="op">~</span><span class="va">key</span>, <span class="op">~</span><span class="va">val_x</span>,</span>
<span>     <span class="fl">1</span>, <span class="st">"x1"</span>,</span>
<span>     <span class="fl">2</span>, <span class="st">"x2"</span>,</span>
<span>     <span class="fl">2</span>, <span class="st">"x3"</span>,</span>
<span>     <span class="fl">3</span>, <span class="st">"x4"</span></span>
<span><span class="op">)</span></span>
<span><span class="va">y</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tribble.html">tribble</a></span><span class="op">(</span></span>
<span>  <span class="op">~</span><span class="va">key</span>, <span class="op">~</span><span class="va">val_y</span>,</span>
<span>     <span class="fl">1</span>, <span class="st">"y1"</span>,</span>
<span>     <span class="fl">2</span>, <span class="st">"y2"</span>,</span>
<span>     <span class="fl">2</span>, <span class="st">"y3"</span>,</span>
<span>     <span class="fl">3</span>, <span class="st">"y4"</span></span>
<span><span class="op">)</span></span>
<span><span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">y</span>, by <span class="op">=</span> <span class="st">"key"</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 6 × 3</span></span>
<span><span class="co">#&gt;     key val_x val_y</span></span>
<span><span class="co">#&gt;   &lt;dbl&gt; &lt;chr&gt; &lt;chr&gt;</span></span>
<span><span class="co">#&gt; 1     1 x1    y1   </span></span>
<span><span class="co">#&gt; 2     2 x2    y2   </span></span>
<span><span class="co">#&gt; 3     2 x2    y3   </span></span>
<span><span class="co">#&gt; 4     2 x3    y2   </span></span>
<span><span class="co">#&gt; 5     2 x3    y3   </span></span>
<span><span class="co">#&gt; 6     3 x4    y4</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</li>
</ol></section><section id="sec-join-by" class="level3" data-number="13.5.4"><h3 data-number="13.5.4" class="anchored" data-anchor-id="sec-join-by">
<span class="header-section-number">13.5.4</span> Defining the key columns</h3>
<p>So far, the pairs of data frames have always been joined by a single variable, and that variable has the same name in both data frames. That constraint was encoded by <code>by = "key"</code>. You can use other values for <code>by</code> to connect the data frames in other ways:</p>
<ul>
<li>
<p>The default, <code>by = NULL</code>, uses all variables that appear in both data frames, the so called <strong>natural</strong> join. For example, the flights and weather data frames match on their common variables: <code>year</code>, <code>month</code>, <code>day</code>, <code>hour</code> and <code>origin</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">flights2</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">weather</span><span class="op">)</span></span>
<span><span class="co">#&gt; Joining, by = c("year", "month", "day", "hour", "origin")</span></span>
<span><span class="co">#&gt; # A tibble: 336,776 × 18</span></span>
<span><span class="co">#&gt;    year month   day  hour origin dest  tailnum carrier  temp  dewp humid wind_…¹</span></span>
<span><span class="co">#&gt;   &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;   &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1  2013     1     1     5 EWR    IAH   N14228  UA       39.0  28.0  64.4     260</span></span>
<span><span class="co">#&gt; 2  2013     1     1     5 LGA    IAH   N24211  UA       39.9  25.0  54.8     250</span></span>
<span><span class="co">#&gt; 3  2013     1     1     5 JFK    MIA   N619AA  AA       39.0  27.0  61.6     260</span></span>
<span><span class="co">#&gt; 4  2013     1     1     5 JFK    BQN   N804JB  B6       39.0  27.0  61.6     260</span></span>
<span><span class="co">#&gt; 5  2013     1     1     6 LGA    ATL   N668DN  DL       39.9  25.0  54.8     260</span></span>
<span><span class="co">#&gt; 6  2013     1     1     5 EWR    ORD   N39463  UA       39.0  28.0  64.4     260</span></span>
<span><span class="co">#&gt; # … with 336,770 more rows, 6 more variables: wind_speed &lt;dbl&gt;,</span></span>
<span><span class="co">#&gt; #   wind_gust &lt;dbl&gt;, precip &lt;dbl&gt;, pressure &lt;dbl&gt;, visib &lt;dbl&gt;,</span></span>
<span><span class="co">#&gt; #   time_hour &lt;dttm&gt;, and abbreviated variable name ¹​wind_dir</span></span>
<span><span class="co">#&gt; # ℹ Use `print(n = ...)` to see more rows, and `colnames()` to see all variable names</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</li>
<li>
<p>A character vector, <code>by = "x"</code>. This is like a natural join, but uses only some of the common variables. For example, <code>flights</code> and <code>planes</code> have <code>year</code> variables, but they mean different things so we only want to join by <code>tailnum</code>.</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">flights2</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">planes</span>, by <span class="op">=</span> <span class="st">"tailnum"</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 336,776 × 16</span></span>
<span><span class="co">#&gt;   year.x month   day  hour origin dest  tailnum carrier year.y type      manuf…¹</span></span>
<span><span class="co">#&gt;    &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;    &lt;int&gt; &lt;chr&gt;     &lt;chr&gt;  </span></span>
<span><span class="co">#&gt; 1   2013     1     1     5 EWR    IAH   N14228  UA        1999 Fixed wi… BOEING </span></span>
<span><span class="co">#&gt; 2   2013     1     1     5 LGA    IAH   N24211  UA        1998 Fixed wi… BOEING </span></span>
<span><span class="co">#&gt; 3   2013     1     1     5 JFK    MIA   N619AA  AA        1990 Fixed wi… BOEING </span></span>
<span><span class="co">#&gt; 4   2013     1     1     5 JFK    BQN   N804JB  B6        2012 Fixed wi… AIRBUS </span></span>
<span><span class="co">#&gt; 5   2013     1     1     6 LGA    ATL   N668DN  DL        1991 Fixed wi… BOEING </span></span>
<span><span class="co">#&gt; 6   2013     1     1     5 EWR    ORD   N39463  UA        2012 Fixed wi… BOEING </span></span>
<span><span class="co">#&gt; # … with 336,770 more rows, 5 more variables: model &lt;chr&gt;, engines &lt;int&gt;,</span></span>
<span><span class="co">#&gt; #   seats &lt;int&gt;, speed &lt;int&gt;, engine &lt;chr&gt;, and abbreviated variable name</span></span>
<span><span class="co">#&gt; #   ¹​manufacturer</span></span>
<span><span class="co">#&gt; # ℹ Use `print(n = ...)` to see more rows, and `colnames()` to see all variable names</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note that the <code>year</code> variables (which appear in both input data frames, but are not constrained to be equal) are disambiguated in the output with a suffix.</p>
</li>
<li>
<p>A named character vector: <code>by = c("a" = "b")</code>. This will match variable <code>a</code> in data frame <code>x</code> to variable <code>b</code> in data frame <code>y</code>. The variables from <code>x</code> will be used in the output.</p>
<p>For example, if we want to draw a map we need to combine the flights data with the airports data which contains the location (<code>lat</code> and <code>lon</code>) of each airport. Each flight has an origin and destination <code>airport</code>, so we need to specify which one we want to join to:</p>
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">flights2</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">airports</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"dest"</span> <span class="op">=</span> <span class="st">"faa"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 336,776 × 15</span></span>
<span><span class="co">#&gt;    year month   day  hour origin dest  tailnum carrier name      lat   lon   alt</span></span>
<span><span class="co">#&gt;   &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1  2013     1     1     5 EWR    IAH   N14228  UA      George…  30.0 -95.3    97</span></span>
<span><span class="co">#&gt; 2  2013     1     1     5 LGA    IAH   N24211  UA      George…  30.0 -95.3    97</span></span>
<span><span class="co">#&gt; 3  2013     1     1     5 JFK    MIA   N619AA  AA      Miami …  25.8 -80.3     8</span></span>
<span><span class="co">#&gt; 4  2013     1     1     5 JFK    BQN   N804JB  B6      &lt;NA&gt;     NA    NA      NA</span></span>
<span><span class="co">#&gt; 5  2013     1     1     6 LGA    ATL   N668DN  DL      Hartsf…  33.6 -84.4  1026</span></span>
<span><span class="co">#&gt; 6  2013     1     1     5 EWR    ORD   N39463  UA      Chicag…  42.0 -87.9   668</span></span>
<span><span class="co">#&gt; # … with 336,770 more rows, and 3 more variables: tz &lt;dbl&gt;, dst &lt;chr&gt;,</span></span>
<span><span class="co">#&gt; #   tzone &lt;chr&gt;</span></span>
<span><span class="co">#&gt; # ℹ Use `print(n = ...)` to see more rows, and `colnames()` to see all variable names</span></span>
<span></span>
<span><span class="va">flights2</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">airports</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"origin"</span> <span class="op">=</span> <span class="st">"faa"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 336,776 × 15</span></span>
<span><span class="co">#&gt;    year month   day  hour origin dest  tailnum carrier name      lat   lon   alt</span></span>
<span><span class="co">#&gt;   &lt;int&gt; &lt;int&gt; &lt;int&gt; &lt;dbl&gt; &lt;chr&gt;  &lt;chr&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1  2013     1     1     5 EWR    IAH   N14228  UA      Newark…  40.7 -74.2    18</span></span>
<span><span class="co">#&gt; 2  2013     1     1     5 LGA    IAH   N24211  UA      La Gua…  40.8 -73.9    22</span></span>
<span><span class="co">#&gt; 3  2013     1     1     5 JFK    MIA   N619AA  AA      John F…  40.6 -73.8    13</span></span>
<span><span class="co">#&gt; 4  2013     1     1     5 JFK    BQN   N804JB  B6      John F…  40.6 -73.8    13</span></span>
<span><span class="co">#&gt; 5  2013     1     1     6 LGA    ATL   N668DN  DL      La Gua…  40.8 -73.9    22</span></span>
<span><span class="co">#&gt; 6  2013     1     1     5 EWR    ORD   N39463  UA      Newark…  40.7 -74.2    18</span></span>
<span><span class="co">#&gt; # … with 336,770 more rows, and 3 more variables: tz &lt;dbl&gt;, dst &lt;chr&gt;,</span></span>
<span><span class="co">#&gt; #   tzone &lt;chr&gt;</span></span>
<span><span class="co">#&gt; # ℹ Use `print(n = ...)` to see more rows, and `colnames()` to see all variable names</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</li>
</ul></section><section id="exercises-2" class="level3" data-number="13.5.5"><h3 data-number="13.5.5" class="anchored" data-anchor-id="exercises-2">
<span class="header-section-number">13.5.5</span> Exercises</h3>
<ol type="1">
<li>
<p>Compute the average delay by destination, then join on the <code>airports</code> data frame so you can show the spatial distribution of delays. Here’s an easy way to draw a map of the United States:</p>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">airports</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter-joins.html">semi_join</a></span><span class="op">(</span><span class="va">flights</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"faa"</span> <span class="op">=</span> <span class="st">"dest"</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/ggplot.html">ggplot</a></span><span class="op">(</span><span class="fu"><a href="https://ggplot2.tidyverse.org/reference/aes.html">aes</a></span><span class="op">(</span><span class="va">lon</span>, <span class="va">lat</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/borders.html">borders</a></span><span class="op">(</span><span class="st">"state"</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/geom_point.html">geom_point</a></span><span class="op">(</span><span class="op">)</span> <span class="op">+</span></span>
<span>    <span class="fu"><a href="https://ggplot2.tidyverse.org/reference/coord_map.html">coord_quickmap</a></span><span class="op">(</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>(Don’t worry if you don’t understand what <code><a href="https://dplyr.tidyverse.org/reference/filter-joins.html">semi_join()</a></code> does — you’ll learn about it next.)</p>
<p>You might want to use the <code>size</code> or <code>colour</code> of the points to display the average delay for each airport.</p>
</li>
<li><p>Add the location of the origin <em>and</em> destination (i.e.&nbsp;the <code>lat</code> and <code>lon</code>) to <code>flights</code>.</p></li>
<li><p>Is there a relationship between the age of a plane and its delays?</p></li>
<li><p>What weather conditions make it more likely to see a delay?</p></li>
<li><p>What happened on June 13 2013? Display the spatial pattern of delays, and then use Google to cross-reference with the weather.</p></li>
</ol></section></section><section id="non-equi-joins" class="level2" data-number="13.6"><h2 data-number="13.6" class="anchored" data-anchor-id="non-equi-joins">
<span class="header-section-number">13.6</span> Non-equi joins</h2>
<p><code>join_by()</code></p>
<p>Rolling joins</p>
<p>Overlap joins</p>
</section><section id="sec-filtering-joins" class="level2" data-number="13.7"><h2 data-number="13.7" class="anchored" data-anchor-id="sec-filtering-joins">
<span class="header-section-number">13.7</span> Filtering joins</h2>
<p>Filtering joins match observations in the same way as mutating joins, but affect the observations, not the variables. There are two types:</p>
<ul>
<li>
<code>semi_join(x, y)</code> <strong>keeps</strong> all observations in <code>x</code> that have a match in <code>y</code>.</li>
<li>
<code>anti_join(x, y)</code> <strong>drops</strong> all observations in <code>x</code> that have a match in <code>y</code>.</li>
</ul>
<p>Semi-joins are useful for matching filtered summary data frames back to the original rows. For example, imagine you’ve found the top ten most popular destinations:</p>
<div class="cell">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">top_dest</span> <span class="op">&lt;-</span> <span class="va">flights</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">dest</span>, sort <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="fl">10</span><span class="op">)</span></span>
<span><span class="va">top_dest</span></span>
<span><span class="co">#&gt; # A tibble: 10 × 2</span></span>
<span><span class="co">#&gt;   dest      n</span></span>
<span><span class="co">#&gt;   &lt;chr&gt; &lt;int&gt;</span></span>
<span><span class="co">#&gt; 1 ORD   17283</span></span>
<span><span class="co">#&gt; 2 ATL   17215</span></span>
<span><span class="co">#&gt; 3 LAX   16174</span></span>
<span><span class="co">#&gt; 4 BOS   15508</span></span>
<span><span class="co">#&gt; 5 MCO   14082</span></span>
<span><span class="co">#&gt; 6 CLT   14064</span></span>
<span><span class="co">#&gt; # … with 4 more rows</span></span>
<span><span class="co">#&gt; # ℹ Use `print(n = ...)` to see more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now you want to find each flight that went to one of those destinations. You could construct a filter yourself:</p>
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">flights</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">dest</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="va">top_dest</span><span class="op">$</span><span class="va">dest</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 141,145 × 19</span></span>
<span><span class="co">#&gt;    year month   day dep_time sched_dep…¹ dep_d…² arr_t…³ sched…⁴ arr_d…⁵ carrier</span></span>
<span><span class="co">#&gt;   &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;       &lt;int&gt;   &lt;dbl&gt;   &lt;int&gt;   &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;  </span></span>
<span><span class="co">#&gt; 1  2013     1     1      542         540       2     923     850      33 AA     </span></span>
<span><span class="co">#&gt; 2  2013     1     1      554         600      -6     812     837     -25 DL     </span></span>
<span><span class="co">#&gt; 3  2013     1     1      554         558      -4     740     728      12 UA     </span></span>
<span><span class="co">#&gt; 4  2013     1     1      555         600      -5     913     854      19 B6     </span></span>
<span><span class="co">#&gt; 5  2013     1     1      557         600      -3     838     846      -8 B6     </span></span>
<span><span class="co">#&gt; 6  2013     1     1      558         600      -2     753     745       8 AA     </span></span>
<span><span class="co">#&gt; # … with 141,139 more rows, 9 more variables: flight &lt;int&gt;, tailnum &lt;chr&gt;,</span></span>
<span><span class="co">#&gt; #   origin &lt;chr&gt;, dest &lt;chr&gt;, air_time &lt;dbl&gt;, distance &lt;dbl&gt;, hour &lt;dbl&gt;,</span></span>
<span><span class="co">#&gt; #   minute &lt;dbl&gt;, time_hour &lt;dttm&gt;, and abbreviated variable names</span></span>
<span><span class="co">#&gt; #   ¹​sched_dep_time, ²​dep_delay, ³​arr_time, ⁴​sched_arr_time, ⁵​arr_delay</span></span>
<span><span class="co">#&gt; # ℹ Use `print(n = ...)` to see more rows, and `colnames()` to see all variable names</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>But it’s difficult to extend that approach to multiple variables. For example, imagine that you’d found the 10 days with highest average delays. How would you construct the filter statement that used <code>year</code>, <code>month</code>, and <code>day</code> to match it back to <code>flights</code>?</p>
<p>Instead you can use a semi-join, which connects the two data frames like a mutating join, but instead of adding new columns, only keeps the rows in <code>x</code> that have a match in <code>y</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">flights</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter-joins.html">semi_join</a></span><span class="op">(</span><span class="va">top_dest</span><span class="op">)</span></span>
<span><span class="co">#&gt; Joining, by = "dest"</span></span>
<span><span class="co">#&gt; # A tibble: 141,145 × 19</span></span>
<span><span class="co">#&gt;    year month   day dep_time sched_dep…¹ dep_d…² arr_t…³ sched…⁴ arr_d…⁵ carrier</span></span>
<span><span class="co">#&gt;   &lt;int&gt; &lt;int&gt; &lt;int&gt;    &lt;int&gt;       &lt;int&gt;   &lt;dbl&gt;   &lt;int&gt;   &lt;int&gt;   &lt;dbl&gt; &lt;chr&gt;  </span></span>
<span><span class="co">#&gt; 1  2013     1     1      542         540       2     923     850      33 AA     </span></span>
<span><span class="co">#&gt; 2  2013     1     1      554         600      -6     812     837     -25 DL     </span></span>
<span><span class="co">#&gt; 3  2013     1     1      554         558      -4     740     728      12 UA     </span></span>
<span><span class="co">#&gt; 4  2013     1     1      555         600      -5     913     854      19 B6     </span></span>
<span><span class="co">#&gt; 5  2013     1     1      557         600      -3     838     846      -8 B6     </span></span>
<span><span class="co">#&gt; 6  2013     1     1      558         600      -2     753     745       8 AA     </span></span>
<span><span class="co">#&gt; # … with 141,139 more rows, 9 more variables: flight &lt;int&gt;, tailnum &lt;chr&gt;,</span></span>
<span><span class="co">#&gt; #   origin &lt;chr&gt;, dest &lt;chr&gt;, air_time &lt;dbl&gt;, distance &lt;dbl&gt;, hour &lt;dbl&gt;,</span></span>
<span><span class="co">#&gt; #   minute &lt;dbl&gt;, time_hour &lt;dttm&gt;, and abbreviated variable names</span></span>
<span><span class="co">#&gt; #   ¹​sched_dep_time, ²​dep_delay, ³​arr_time, ⁴​sched_arr_time, ⁵​arr_delay</span></span>
<span><span class="co">#&gt; # ℹ Use `print(n = ...)` to see more rows, and `colnames()` to see all variable names</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Graphically, a semi-join looks like this:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="diagrams/join-semi.png" class="img-fluid" alt="Diagram of a semi join. Data frame x is on the left and has two columns (key and val_x) with keys 1, 2, and 3. Diagram y is on the right and also has two columns (key and val_y) with keys 1, 2, and 4. Semi joining these two results in a data frame with two rows and two columns (key and val_x), with keys 1 and 2 (the only keys that match between the two data frames)." width="307"></p>
</div>
</div>
<p>Only the existence of a match is important; it doesn’t matter which observation is matched. This means that filtering joins never duplicate rows like mutating joins do:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="diagrams/join-semi-many.png" class="img-fluid" alt="Diagram of a semi join with data frames with duplicated keys. Data frame x is on the left and has two columns (key and val_x) with keys 1, 2, 2, and 3. Diagram y is on the right and also has two columns (key and val_y) with keys 1, 2, 2, and 3 as well. Semi joining these two results in a data frame with four rows and two columns (key and val_x), with keys 1, 2, 2, and 3 (the matching keys, each appearing as many times as they do in x)." width="312"></p>
</div>
</div>
<p>The inverse of a semi-join is an anti-join. An anti-join keeps the rows that <em>don’t</em> have a match:</p>
<div class="cell">
<div class="cell-output-display">
<p><img src="diagrams/join-anti.png" class="img-fluid" alt="Diagram of an anti join. Data frame x is on the left and has two columns (key and val_x) with keys 1, 2, and 3. Diagram y is on the right and also has two columns (key and val_y) with keys 1, 2, and 4. Anti joining these two results in a data frame with one row and two columns (key and val_x), with keys 3 only (the only key in x that is not in y)." width="307"></p>
</div>
</div>
<p>Anti-joins are useful for diagnosing join mismatches. For example, when connecting <code>flights</code> and <code>planes</code>, you might be interested to know that there are many <code>flights</code> that don’t have a match in <code>planes</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">flights</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter-joins.html">anti_join</a></span><span class="op">(</span><span class="va">planes</span>, by <span class="op">=</span> <span class="st">"tailnum"</span><span class="op">)</span> <span class="op">|&gt;</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">tailnum</span>, sort <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 722 × 2</span></span>
<span><span class="co">#&gt;   tailnum     n</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;   &lt;int&gt;</span></span>
<span><span class="co">#&gt; 1 &lt;NA&gt;     2512</span></span>
<span><span class="co">#&gt; 2 N725MQ    575</span></span>
<span><span class="co">#&gt; 3 N722MQ    513</span></span>
<span><span class="co">#&gt; 4 N723MQ    507</span></span>
<span><span class="co">#&gt; 5 N713MQ    483</span></span>
<span><span class="co">#&gt; 6 N735MQ    396</span></span>
<span><span class="co">#&gt; # … with 716 more rows</span></span>
<span><span class="co">#&gt; # ℹ Use `print(n = ...)` to see more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<section id="exercises-3" class="level3" data-number="13.7.1"><h3 data-number="13.7.1" class="anchored" data-anchor-id="exercises-3">
<span class="header-section-number">13.7.1</span> Exercises</h3>
<ol type="1">
<li><p>What does it mean for a flight to have a missing <code>tailnum</code>? What do the tail numbers that don’t have a matching record in <code>planes</code> have in common? (Hint: one variable explains ~90% of the problems.)</p></li>
<li><p>Filter flights to only show flights with planes that have flown at least 100 flights.</p></li>
<li><p>Combine <code>fueleconomy::vehicles</code> and <code>fueleconomy::common</code> to find only the records for the most common models.</p></li>
<li><p>Find the 48 hours (over the course of the whole year) that have the worst delays. Cross-reference it with the <code>weather</code> data. Can you see any patterns?</p></li>
<li><p>What does <code>anti_join(flights, airports, by = c("dest" = "faa"))</code> tell you? What does <code>anti_join(airports, flights, by = c("faa" = "dest"))</code> tell you?</p></li>
<li><p>You might expect that there’s an implicit relationship between plane and airline, because each plane is flown by a single airline. Confirm or reject this hypothesis using the tools you’ve learned above.</p></li>
</ol></section></section><section id="join-problems" class="level2" data-number="13.8"><h2 data-number="13.8" class="anchored" data-anchor-id="join-problems">
<span class="header-section-number">13.8</span> Join problems</h2>
<p>The data you’ve been working with in this chapter has been cleaned up so that you’ll have as few problems as possible. Your own data is unlikely to be so nice, so there are a few things that you should do with your own data to make your joins go smoothly.</p>
<ol type="1">
<li>
<p>Start by identifying the variables that form the primary key in each data frame. You should usually do this based on your understanding of the data, not empirically by looking for a combination of variables that give a unique identifier. If you just look for variables without thinking about what they mean, you might get (un)lucky and find a combination that’s unique in your current data but the relationship might not be true in general.</p>
<p>For example, the altitude and longitude uniquely identify each airport, but they are not good identifiers!</p>
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">airports</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">alt</span>, <span class="va">lon</span><span class="op">)</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">n</span> <span class="op">&gt;</span> <span class="fl">1</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 0 × 3</span></span>
<span><span class="co">#&gt; # … with 3 variables: alt &lt;dbl&gt;, lon &lt;dbl&gt;, n &lt;int&gt;</span></span>
<span><span class="co">#&gt; # ℹ Use `colnames()` to see all variable names</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</li>
<li><p>Check that none of the variables in the primary key are missing. If a value is missing then it can’t identify an observation!</p></li>
<li>
<p>Check that your foreign keys match primary keys in another data frame. The best way to do this is with an <code><a href="https://dplyr.tidyverse.org/reference/filter-joins.html">anti_join()</a></code>. It’s common for keys not to match because of data entry errors. Fixing these is often a lot of work.</p>
<p>If you do have missing keys, you’ll need to be thoughtful about your use of inner vs.&nbsp;outer joins, carefully considering whether or not you want to drop rows that don’t have a match.</p>
</li>
</ol>
<p>Be aware that simply checking the number of rows before and after the join is not sufficient to ensure that your join has gone smoothly. If you have an inner join with duplicate keys in both data frames, you might get unlucky as the number of dropped rows might exactly equal the number of duplicated rows!</p>


</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./tibble.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Tibbles</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./logicals.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Logical vectors</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">R for Data Science (2e) was written by Hadley Wickham, Mine Çetinkaya-Rundel, and Garrett Grolemund.</div>   
    <div class="nav-footer-right">This book was built with <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>


</body></html>