<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.0.36">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>R for Data Science (2e) - 25&nbsp; Data rectangling</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
span.underline{text-decoration: underline;}
div.column{display: inline-block; vertical-align: top; width: 50%;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./webscraping.html" rel="next">
<link href="./databases.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><script defer="" data-domain="r4ds.hadley.nz" src="https://plausible.io/js/plausible.js"></script>
</head>
<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }"><div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Data rectangling</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation floating overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">R for Data Science (2e)</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/hadley/r4ds/" title="Source Code" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle sidebar-tool" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">Welcome</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./preface-2e.html" class="sidebar-item-text sidebar-link">Preface to the second edition</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./whole-game.html" class="sidebar-item-text sidebar-link">Whole game</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-visualize.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Data visualization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./workflow-basics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Workflow: basics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-transform.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Data transformation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./workflow-pipes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Workflow: Pipes</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-tidy.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Data tidying</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./workflow-style.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Workflow: code style</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./data-import.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Data import</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./workflow-scripts.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Workflow: scripts and projects</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./EDA.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Exploratory Data Analysis</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./workflow-help.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Workflow: Getting help</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./transform.html" class="sidebar-item-text sidebar-link">Transform</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./tibble.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Tibbles</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./joins.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Joins</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./logicals.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Logical vectors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./numbers.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Numbers</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./strings.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">16</span>&nbsp; <span class="chapter-title">Strings</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./regexps.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">17</span>&nbsp; <span class="chapter-title">Regular expressions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./factors.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">18</span>&nbsp; <span class="chapter-title">Factors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./datetimes.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">19</span>&nbsp; <span class="chapter-title">Dates and times</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./missing-values.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">20</span>&nbsp; <span class="chapter-title">Missing values</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./column-wise.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">21</span>&nbsp; <span class="chapter-title">Column-wise operations</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./wrangle.html" class="sidebar-item-text sidebar-link">Wrangle</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./parsing.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">22</span>&nbsp; <span class="chapter-title">Parsing</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./spreadsheets.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">23</span>&nbsp; <span class="chapter-title">Spreadsheets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./databases.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Databases</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rectangling.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Data rectangling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./webscraping.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Web scraping</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./program.html" class="sidebar-item-text sidebar-link">Program</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./functions.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">27</span>&nbsp; <span class="chapter-title">Functions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./vectors.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">28</span>&nbsp; <span class="chapter-title">Vectors</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./iteration.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">29</span>&nbsp; <span class="chapter-title">Iteration</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./prog-strings.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">30</span>&nbsp; <span class="chapter-title">Programming with strings</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a href="./communicate.html" class="sidebar-item-text sidebar-link">Communicate</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-5" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-5" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rmarkdown.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">31</span>&nbsp; <span class="chapter-title">R Markdown</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./communicate-plots.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">32</span>&nbsp; <span class="chapter-title">Graphics for communication</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rmarkdown-formats.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">33</span>&nbsp; <span class="chapter-title">R Markdown formats</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./rmarkdown-workflow.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">34</span>&nbsp; <span class="chapter-title">R Markdown workflow</span></a>
  </div>
</li>
      </ul>
</li>
    </ul>
</div>
</nav><!-- margin-sidebar --><div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc"><h2 id="toc-title">Table of contents</h2>
   
  <ul>
<li>
<a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"> <span class="header-section-number">25.1</span> Introduction</a>
  <ul class="collapse">
<li><a href="#prerequisites" id="toc-prerequisites" class="nav-link" data-scroll-target="#prerequisites"> <span class="header-section-number">25.1.1</span> Prerequisites</a></li>
  </ul>
</li>
  <li>
<a href="#lists" id="toc-lists" class="nav-link" data-scroll-target="#lists"> <span class="header-section-number">25.2</span> Lists</a>
  <ul class="collapse">
<li><a href="#hierarchy" id="toc-hierarchy" class="nav-link" data-scroll-target="#hierarchy"> <span class="header-section-number">25.2.1</span> Hierarchy</a></li>
  <li><a href="#list-columns" id="toc-list-columns" class="nav-link" data-scroll-target="#list-columns"> <span class="header-section-number">25.2.2</span> List-columns</a></li>
  </ul>
</li>
  <li>
<a href="#unnesting" id="toc-unnesting" class="nav-link" data-scroll-target="#unnesting"> <span class="header-section-number">25.3</span> Unnesting</a>
  <ul class="collapse">
<li><a href="#unnest_wider" id="toc-unnest_wider" class="nav-link" data-scroll-target="#unnest_wider"> <span class="header-section-number">25.3.1</span> <code>unnest_wider()</code></a></li>
  <li><a href="#unnest_longer" id="toc-unnest_longer" class="nav-link" data-scroll-target="#unnest_longer"> <span class="header-section-number">25.3.2</span> <code>unnest_longer()</code></a></li>
  <li><a href="#inconsistent-types" id="toc-inconsistent-types" class="nav-link" data-scroll-target="#inconsistent-types"> <span class="header-section-number">25.3.3</span> Inconsistent types</a></li>
  <li><a href="#other-functions" id="toc-other-functions" class="nav-link" data-scroll-target="#other-functions"> <span class="header-section-number">25.3.4</span> Other functions</a></li>
  <li><a href="#exercises" id="toc-exercises" class="nav-link" data-scroll-target="#exercises"> <span class="header-section-number">25.3.5</span> Exercises</a></li>
  </ul>
</li>
  <li>
<a href="#case-studies" id="toc-case-studies" class="nav-link" data-scroll-target="#case-studies"> <span class="header-section-number">25.4</span> Case studies</a>
  <ul class="collapse">
<li><a href="#very-wide-data" id="toc-very-wide-data" class="nav-link" data-scroll-target="#very-wide-data"> <span class="header-section-number">25.4.1</span> Very wide data</a></li>
  <li><a href="#relational-data" id="toc-relational-data" class="nav-link" data-scroll-target="#relational-data"> <span class="header-section-number">25.4.2</span> Relational data</a></li>
  <li><a href="#a-dash-of-text-analysis" id="toc-a-dash-of-text-analysis" class="nav-link" data-scroll-target="#a-dash-of-text-analysis"> <span class="header-section-number">25.4.3</span> A dash of text analysis</a></li>
  <li><a href="#deeply-nested" id="toc-deeply-nested" class="nav-link" data-scroll-target="#deeply-nested"> <span class="header-section-number">25.4.4</span> Deeply nested</a></li>
  </ul>
</li>
  <li>
<a href="#r-locations-selectcity-formatted_address-geometry-unnest_widergeometry-selectlocationviewport-unnest_widerbounds-renamene-northeast-sw-southwest-unnest_widercne-sw-names_sep-_" id="toc-r-locations-selectcity-formatted_address-geometry-unnest_widergeometry-selectlocationviewport-unnest_widerbounds-renamene-northeast-sw-southwest-unnest_widercne-sw-names_sep-_" class="nav-link" data-scroll-target="#r-locations-selectcity-formatted_address-geometry-unnest_widergeometry-selectlocationviewport-unnest_widerbounds-renamene-northeast-sw-southwest-unnest_widercne-sw-names_sep-_"> <span class="header-section-number">26</span> <code>{r} # locations |&gt;  #   select(city, formatted_address, geometry) |&gt;  #   unnest_wider(geometry) |&gt;  #   select(!location:viewport) |&gt; #   unnest_wider(bounds) |&gt;  #   rename(ne = northeast, sw = southwest) |&gt;  #   unnest_wider(c(ne, sw), names_sep = "_")</code></a>
  <ul class="collapse">
<li><a href="#exercises-1" id="toc-exercises-1" class="nav-link" data-scroll-target="#exercises-1"> <span class="header-section-number">26.0.1</span> Exercises</a></li>
  <li>
<a href="#json" id="toc-json" class="nav-link" data-scroll-target="#json"> <span class="header-section-number">26.1</span> JSON</a>
  <ul class="collapse">
<li><a href="#data-types" id="toc-data-types" class="nav-link" data-scroll-target="#data-types"> <span class="header-section-number">26.1.1</span> Data types</a></li>
  <li><a href="#jsonlite" id="toc-jsonlite" class="nav-link" data-scroll-target="#jsonlite"> <span class="header-section-number">26.1.2</span> jsonlite</a></li>
  <li><a href="#starting-the-rectangling-process" id="toc-starting-the-rectangling-process" class="nav-link" data-scroll-target="#starting-the-rectangling-process"> <span class="header-section-number">26.1.3</span> Starting the rectangling process</a></li>
  <li><a href="#translation-challenges" id="toc-translation-challenges" class="nav-link" data-scroll-target="#translation-challenges"> <span class="header-section-number">26.1.4</span> Translation challenges</a></li>
  <li><a href="#exercises-2" id="toc-exercises-2" class="nav-link" data-scroll-target="#exercises-2"> <span class="header-section-number">26.1.5</span> Exercises</a></li>
  </ul>
</li>
  </ul>
</li>
  </ul><div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/hadley/r4ds/edit/main/rectangling.qmd" class="toc-action">Edit this page</a></p><p><a href="https://github.com/hadley/r4ds/issues/new" class="toc-action">Report an issue</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<h1 class="title"><span id="sec-rectangling" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">25</span>&nbsp; <span class="chapter-title">Data rectangling</span></span></h1>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header><div class="status">
<p>You are reading the work-in-progress second edition of R for Data Science. This chapter should be readable but is currently undergoing final polishing. You can find the complete first edition at <a href="https://r4ds.had.co.nz" class="uri">https://r4ds.had.co.nz</a>.</p>
</div>
<section id="introduction" class="level2" data-number="25.1"><h2 data-number="25.1" class="anchored" data-anchor-id="introduction">
<span class="header-section-number">25.1</span> Introduction</h2>
<p>In this chapter, you’ll learn the art of data <strong>rectangling</strong>, taking data that is fundamentally tree-like and converting it into a rectangular data frames made up of rows and columns. This is important because hierarchical data is surprisingly common, especially when working with data that comes from a web API.</p>
<p>To learn about rectangling, you’ll first learn about lists, the data structure that makes hierarchical data possible in R. Then you’ll learn about two crucial tidyr functions: <code><a href="https://tidyr.tidyverse.org/reference/hoist.html">tidyr::unnest_longer()</a></code>, which converts children in rows, and <code><a href="https://tidyr.tidyverse.org/reference/hoist.html">tidyr::unnest_wider()</a></code>, which converts children into columns. We’ll then show you a few case studies, applying these simple function multiple times to solve real problems. We’ll finish off by talking about JSON, the most frequent source of hierarchical datasets and a common format for data exchange on the web.</p>
<section id="prerequisites" class="level3" data-number="25.1.1"><h3 data-number="25.1.1" class="anchored" data-anchor-id="prerequisites">
<span class="header-section-number">25.1.1</span> Prerequisites</h3>
<p>In this chapter we’ll use many functions from tidyr, a core member of the tidyverse. We’ll also use repurrrsive to provide some interesting datasets rectangling practice, and we’ll finish up with a little jsonlite, which we’ll use to read JSON files into R lists.</p>
<div class="cell">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/jennybc/repurrrsive">repurrrsive</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://arxiv.org/abs/1403.2805">jsonlite</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section></section><section id="lists" class="level2" data-number="25.2"><h2 data-number="25.2" class="anchored" data-anchor-id="lists">
<span class="header-section-number">25.2</span> Lists</h2>
<p>So far we’ve used simple vectors like integers, numbers, characters, date-times, and factors. These vectors are simple because they’re homogeneous: every element is same type. If you want to store element of different types in the same vector, you’ll need a <strong>list</strong>, which you create with <code><a href="https://rdrr.io/r/base/list.html">list()</a></code>:</p>
<div class="cell">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">x1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">4</span>, <span class="st">"a"</span>, <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="va">x1</span></span>
<span><span class="co">#&gt; [[1]]</span></span>
<span><span class="co">#&gt; [1] 1 2 3 4</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; [[2]]</span></span>
<span><span class="co">#&gt; [1] "a"</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; [[3]]</span></span>
<span><span class="co">#&gt; [1] TRUE</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>It’s often convenient to name the components, or <strong>children</strong>, of a list, which you can do in the same way as naming the columns of a tibble:</p>
<div class="cell">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">x2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>a <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="fl">2</span>, b <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="fl">3</span>, c <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="fl">4</span><span class="op">)</span></span>
<span><span class="va">x2</span></span>
<span><span class="co">#&gt; $a</span></span>
<span><span class="co">#&gt; [1] 1 2</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; $b</span></span>
<span><span class="co">#&gt; [1] 1 2 3</span></span>
<span><span class="co">#&gt; </span></span>
<span><span class="co">#&gt; $c</span></span>
<span><span class="co">#&gt; [1] 1 2 3 4</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Even for these very simple lists, printing takes up quite a lot of space. A useful alternative is <code><a href="https://rdrr.io/r/utils/str.html">str()</a></code>, which generates a compact display of the <strong>str</strong>ucture, de-emphasizing the contents:</p>
<div class="cell">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">x1</span><span class="op">)</span></span>
<span><span class="co">#&gt; List of 3</span></span>
<span><span class="co">#&gt;  $ : int [1:4] 1 2 3 4</span></span>
<span><span class="co">#&gt;  $ : chr "a"</span></span>
<span><span class="co">#&gt;  $ : logi TRUE</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">x2</span><span class="op">)</span></span>
<span><span class="co">#&gt; List of 3</span></span>
<span><span class="co">#&gt;  $ a: int [1:2] 1 2</span></span>
<span><span class="co">#&gt;  $ b: int [1:3] 1 2 3</span></span>
<span><span class="co">#&gt;  $ c: int [1:4] 1 2 3 4</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As you can see, <code><a href="https://rdrr.io/r/utils/str.html">str()</a></code> displays each child of the list on its own line. It displays the name, if present, then an abbreviation of the type, then the first few values.</p>
<section id="hierarchy" class="level3" data-number="25.2.1"><h3 data-number="25.2.1" class="anchored" data-anchor-id="hierarchy">
<span class="header-section-number">25.2.1</span> Hierarchy</h3>
<p>Lists can contain any type of object, including other lists. This makes them suitable for representing hierarchical (tree-like) structures:</p>
<div class="cell">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">x3</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">4</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">x3</span><span class="op">)</span></span>
<span><span class="co">#&gt; List of 2</span></span>
<span><span class="co">#&gt;  $ :List of 2</span></span>
<span><span class="co">#&gt;   ..$ : num 1</span></span>
<span><span class="co">#&gt;   ..$ : num 2</span></span>
<span><span class="co">#&gt;  $ :List of 2</span></span>
<span><span class="co">#&gt;   ..$ : num 3</span></span>
<span><span class="co">#&gt;   ..$ : num 4</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This is notably different to <code><a href="https://rdrr.io/r/base/c.html">c()</a></code>, which generates a flat vector:</p>
<div class="cell">
<div class="sourceCode" id="cb6"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">4</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] 1 2 3 4</span></span>
<span></span>
<span><span class="va">x4</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">4</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">x4</span><span class="op">)</span></span>
<span><span class="co">#&gt; List of 4</span></span>
<span><span class="co">#&gt;  $ : num 1</span></span>
<span><span class="co">#&gt;  $ : num 2</span></span>
<span><span class="co">#&gt;  $ : num 3</span></span>
<span><span class="co">#&gt;  $ : num 4</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As lists get more complex, <code><a href="https://rdrr.io/r/utils/str.html">str()</a></code> gets more useful, as it lets you see the hierarchy at a glance:</p>
<div class="cell">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">x5</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="fl">2</span>, <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="fl">4</span>, <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="fl">5</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="va">x5</span><span class="op">)</span></span>
<span><span class="co">#&gt; List of 2</span></span>
<span><span class="co">#&gt;  $ : num 1</span></span>
<span><span class="co">#&gt;  $ :List of 2</span></span>
<span><span class="co">#&gt;   ..$ : num 2</span></span>
<span><span class="co">#&gt;   ..$ :List of 2</span></span>
<span><span class="co">#&gt;   .. ..$ : num 3</span></span>
<span><span class="co">#&gt;   .. ..$ :List of 2</span></span>
<span><span class="co">#&gt;   .. .. ..$ : num 4</span></span>
<span><span class="co">#&gt;   .. .. ..$ :List of 1</span></span>
<span><span class="co">#&gt;   .. .. .. ..$ : num 5</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As lists get even large and more complex, even <code><a href="https://rdrr.io/r/utils/str.html">str()</a></code> starts to fail, you’ll need to switch to <code><a href="https://rdrr.io/r/utils/View.html">View()</a></code><a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>. <a href="#fig-view-collapsed">Figure&nbsp;<span>25.1</span></a> shows the result of calling <code>View(x4)</code>. The viewer starts by showing just the top level of the list, but you can interactively expand any of the components to see more, as in <a href="#fig-view-expand-1">Figure&nbsp;<span>25.2</span></a>. RStudio will also show you the code you need to access that element, as in <a href="#fig-view-expand-2">Figure&nbsp;<span>25.3</span></a>. We’ll come back to how this code works in <a href="vectors.html#sec-vector-subsetting"><span>Section&nbsp;28.4.5</span></a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-view-collapsed" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="screenshots/View-1.png" class="img-fluid figure-img" width="689"></p>
<p></p><figcaption class="figure-caption">Figure 25.1: The RStudio allows you to interactively explore a complex list. The viewer opens showing only the top level of the list.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-view-expand-1" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="screenshots/View-2.png" class="img-fluid figure-img" width="689"></p>
<p></p><figcaption class="figure-caption">Figure 25.2: Clicking on the rightward facing triangle expands that component of the list so that you can also see its children.</figcaption><p></p>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<div id="fig-view-expand-2" class="quarto-figure quarto-figure-center anchored">
<figure class="figure"><p><img src="screenshots/View-3.png" class="img-fluid figure-img" width="689"></p>
<p></p><figcaption class="figure-caption">Figure 25.3: You can repeat this operation as many times as needed to get to the data you’re interested in. Note the bottom-right corner: if you click an element of the list, RStudio will give you the subsetting code needed to access it, in this case <code>x4[[2]][[2]][[2]]</code>.</figcaption><p></p>
</figure>
</div>
</div>
</div>
</section><section id="list-columns" class="level3" data-number="25.2.2"><h3 data-number="25.2.2" class="anchored" data-anchor-id="list-columns">
<span class="header-section-number">25.2.2</span> List-columns</h3>
<p>Lists can also live inside a tibble, where we call them list-columns. List-columns are useful because they allow you to shoehorn in objects that wouldn’t wouldn’t usually belong in a tibble. In particular, list-columns are are used a lot in the <a href="https://www.tidymodels.org">tidymodels</a> ecosystem, because they allows you to store things like models or resamples in a data frame.</p>
<p>Here’s a simple example of a list-column:</p>
<div class="cell">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span></span>
<span>  x <span class="op">=</span> <span class="fl">1</span><span class="op">:</span><span class="fl">2</span>, </span>
<span>  y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"a"</span>, <span class="st">"b"</span><span class="op">)</span>,</span>
<span>  z <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="fl">3</span>, <span class="fl">4</span>, <span class="fl">5</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span><span class="va">df</span></span>
<span><span class="co">#&gt; # A tibble: 2 × 3</span></span>
<span><span class="co">#&gt;       x y     z         </span></span>
<span><span class="co">#&gt;   &lt;int&gt; &lt;chr&gt; &lt;list&gt;    </span></span>
<span><span class="co">#&gt; 1     1 a     &lt;list [2]&gt;</span></span>
<span><span class="co">#&gt; 2     2 b     &lt;list [3]&gt;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>There’s nothing special about lists in a tibble; they behave like any other column:</p>
<div class="cell">
<div class="sourceCode" id="cb9"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">df</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">x</span> <span class="op">==</span> <span class="fl">1</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 1 × 3</span></span>
<span><span class="co">#&gt;       x y     z         </span></span>
<span><span class="co">#&gt;   &lt;int&gt; &lt;chr&gt; &lt;list&gt;    </span></span>
<span><span class="co">#&gt; 1     1 a     &lt;list [2]&gt;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Computing with list-columns is harder, but that’s because computing with lists is harder in general; we’ll come back to that in <a href="iteration.html"><span>Chapter&nbsp;29</span></a>. In this chapter, we’ll focus on unnesting list-columns out into regular variables so you can use your existing tools on them.</p>
<p>The default print method just displays a rough summary of the contents. The list column could be arbitrarily complex, so there’s no good way to print it. If you want to see it, you’ll need to pull the list-column out and apply one of the techniques that you learned above:</p>
<div class="cell">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">df</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">x</span> <span class="op">==</span> <span class="fl">1</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/pull.html">pull</a></span><span class="op">(</span><span class="va">z</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; List of 1</span></span>
<span><span class="co">#&gt;  $ :List of 2</span></span>
<span><span class="co">#&gt;   ..$ : num 1</span></span>
<span><span class="co">#&gt;   ..$ : num 2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Similarly, if you <code><a href="https://rdrr.io/r/utils/View.html">View()</a></code> a data frame in RStudio, you’ll get the standard tabular view, which doesn’t allow you to selectively expand list columns. To explore those fields you’ll need to <code><a href="https://dplyr.tidyverse.org/reference/pull.html">pull()</a></code> and view, e.g.&nbsp;<code>df |&gt; pull(z) |&gt; View()</code>.</p>
<div class="callout-note callout callout-style-simple callout-captioned">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-caption-container flex-fill">
Base R
</div>
</div>
<div class="callout-body-container callout-body">
<p>It’s possible to put a list in a column of a <code>data.frame</code>, but it’s a lot fiddlier because <code><a href="https://rdrr.io/r/base/data.frame.html">data.frame()</a></code> treats a list as a list of columns:</p>
<div class="cell">
<div class="sourceCode" id="cb11"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span>x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">3</span>, <span class="fl">3</span><span class="op">:</span><span class="fl">5</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt;   x.1.3 x.3.5</span></span>
<span><span class="co">#&gt; 1     1     3</span></span>
<span><span class="co">#&gt; 2     2     4</span></span>
<span><span class="co">#&gt; 3     3     5</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You can force <code><a href="https://rdrr.io/r/base/data.frame.html">data.frame()</a></code> to treat a list as a list of rows by wrapping it in list <code><a href="https://rdrr.io/r/base/AsIs.html">I()</a></code>, but the result doesn’t print particularly usefully:</p>
<div class="cell">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/base/data.frame.html">data.frame</a></span><span class="op">(</span></span>
<span>  x <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/AsIs.html">I</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="fl">1</span><span class="op">:</span><span class="fl">3</span>, <span class="fl">3</span><span class="op">:</span><span class="fl">5</span><span class="op">)</span><span class="op">)</span>, </span>
<span>  y <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"1, 2"</span>, <span class="st">"3, 4, 5"</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span><span class="co">#&gt;         x       y</span></span>
<span><span class="co">#&gt; 1 1, 2, 3    1, 2</span></span>
<span><span class="co">#&gt; 2 3, 4, 5 3, 4, 5</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>It’s easier to use list-columns with tibbles because <code><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble()</a></code> treats lists like either vectors and the print method has been designed with lists in mind.</p>
</div>
</div>
</section></section><section id="unnesting" class="level2" data-number="25.3"><h2 data-number="25.3" class="anchored" data-anchor-id="unnesting">
<span class="header-section-number">25.3</span> Unnesting</h2>
<p>Now that you’ve learned the basics of lists and list-columns, lets explore how you can turn them back into regular rows and columns. We’ll start with very simple sample data so you can get the basic idea, and then switch to more realistic examples in the next section.</p>
<p>List-columns tend to come in two basic forms: named and unnamed. When the children are <strong>named</strong>, they tend to have the same names in every row. When the children are <strong>unnamed</strong>, the number of elements tends to vary from row-to-row. The following code creates an example of each. In <code>df1</code>, every element of list-column <code>y</code> has two elements named <code>a</code> and <code>b</code>. If <code>df2</code>, the elements of list-column <code>y</code> are unnamed and vary in length.</p>
<div class="cell">
<div class="sourceCode" id="cb13"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">df1</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tribble.html">tribble</a></span><span class="op">(</span></span>
<span>  <span class="op">~</span><span class="va">x</span>, <span class="op">~</span><span class="va">y</span>,</span>
<span>  <span class="fl">1</span>, <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>a <span class="op">=</span> <span class="fl">11</span>, b <span class="op">=</span> <span class="fl">12</span><span class="op">)</span>,</span>
<span>  <span class="fl">2</span>, <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>a <span class="op">=</span> <span class="fl">21</span>, b <span class="op">=</span> <span class="fl">22</span><span class="op">)</span>,</span>
<span>  <span class="fl">3</span>, <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>a <span class="op">=</span> <span class="fl">31</span>, b <span class="op">=</span> <span class="fl">32</span><span class="op">)</span>,</span>
<span><span class="op">)</span></span>
<span></span>
<span><span class="va">df2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tribble.html">tribble</a></span><span class="op">(</span></span>
<span>  <span class="op">~</span><span class="va">x</span>, <span class="op">~</span><span class="va">y</span>,</span>
<span>  <span class="fl">1</span>, <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="fl">11</span>, <span class="fl">12</span>, <span class="fl">13</span><span class="op">)</span>,</span>
<span>  <span class="fl">2</span>, <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="fl">21</span><span class="op">)</span>,</span>
<span>  <span class="fl">3</span>, <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="fl">31</span>, <span class="fl">32</span><span class="op">)</span>,</span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Named list-columns naturally unnest into columns: each named element becomes a new named column. Unnamed list-columns naturally unnested in to rows: you’ll get one row for each child. tidyr provides two functions for these two case: <code><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_wider()</a></code> and <code><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer()</a></code>. The following sections explain how they work.</p>
<section id="unnest_wider" class="level3" data-number="25.3.1"><h3 data-number="25.3.1" class="anchored" data-anchor-id="unnest_wider">
<span class="header-section-number">25.3.1</span> <code>unnest_wider()</code>
</h3>
<p>When each row has the same number of elements with the same names, like <code>df1</code>, it’s natural to put each component into its own column with <code><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_wider()</a></code>:</p>
<div class="cell">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">df1</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_wider</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 3 × 3</span></span>
<span><span class="co">#&gt;       x     a     b</span></span>
<span><span class="co">#&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1     1    11    12</span></span>
<span><span class="co">#&gt; 2     2    21    22</span></span>
<span><span class="co">#&gt; 3     3    31    32</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>By default, the names of the new columns come exclusively from the names of the list, but you can use the <code>names_sep</code> argument to request that they combine the column name and the list names. This is useful for disambiguating repeated names.</p>
<div class="cell">
<div class="sourceCode" id="cb15"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">df1</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_wider</a></span><span class="op">(</span><span class="va">y</span>, names_sep <span class="op">=</span> <span class="st">"_"</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 3 × 3</span></span>
<span><span class="co">#&gt;       x   y_a   y_b</span></span>
<span><span class="co">#&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1     1    11    12</span></span>
<span><span class="co">#&gt; 2     2    21    22</span></span>
<span><span class="co">#&gt; 3     3    31    32</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We can also use <code><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_wider()</a></code> with unnamed list-columns, as in <code>df2</code>. Since columns require names but the list lacks them, <code><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_wider()</a></code> will label them with consecutive integers:</p>
<div class="cell">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">df2</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_wider</a></span><span class="op">(</span><span class="va">y</span>, names_sep <span class="op">=</span> <span class="st">"_"</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 3 × 4</span></span>
<span><span class="co">#&gt;       x   y_1   y_2   y_3</span></span>
<span><span class="co">#&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt; &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1     1    11    12    13</span></span>
<span><span class="co">#&gt; 2     2    21    NA    NA</span></span>
<span><span class="co">#&gt; 3     3    31    32    NA</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You’ll notice that <code>unnested_wider()</code>, much like <code><a href="https://tidyr.tidyverse.org/reference/pivot_wider.html">pivot_wider()</a></code>, turns implicit missing values in to explicit missing values.</p>
</section><section id="unnest_longer" class="level3" data-number="25.3.2"><h3 data-number="25.3.2" class="anchored" data-anchor-id="unnest_longer">
<span class="header-section-number">25.3.2</span> <code>unnest_longer()</code>
</h3>
<p>When each row contains an unnamed list, it’s most natural to put each element into its own row with <code><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer()</a></code>:</p>
<div class="cell">
<div class="sourceCode" id="cb17"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">df2</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 6 × 2</span></span>
<span><span class="co">#&gt;       x     y</span></span>
<span><span class="co">#&gt;   &lt;dbl&gt; &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1     1    11</span></span>
<span><span class="co">#&gt; 2     1    12</span></span>
<span><span class="co">#&gt; 3     1    13</span></span>
<span><span class="co">#&gt; 4     2    21</span></span>
<span><span class="co">#&gt; 5     3    31</span></span>
<span><span class="co">#&gt; 6     3    32</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Note how <code>x</code> is duplicated for each element inside of <code>y</code>: we get one row of output for each element inside the list-column. But what happens if the list-column is empty, as in the following example?</p>
<div class="cell">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">df6</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tribble.html">tribble</a></span><span class="op">(</span></span>
<span>  <span class="op">~</span><span class="va">x</span>, <span class="op">~</span><span class="va">y</span>,</span>
<span>  <span class="st">"a"</span>, <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">2</span><span class="op">)</span>,</span>
<span>  <span class="st">"b"</span>, <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="fl">3</span><span class="op">)</span>,</span>
<span>  <span class="st">"c"</span>, <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="op">)</span></span>
<span><span class="va">df6</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 3 × 2</span></span>
<span><span class="co">#&gt;   x         y</span></span>
<span><span class="co">#&gt;   &lt;chr&gt; &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 a         1</span></span>
<span><span class="co">#&gt; 2 a         2</span></span>
<span><span class="co">#&gt; 3 b         3</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We get zero rows in the output, so the row effectively disappears. Once <a href="https://github.com/tidyverse/tidyr/issues/1339" class="uri">https://github.com/tidyverse/tidyr/issues/1339</a> is fixed, you’ll be able to keep this row, replacing <code>y</code> with <code>NA</code> by setting <code>keep_empty = TRUE</code>.</p>
<p>You can also unnest named list-columns, like <code>df1$y</code> into the rows. Because the elements are named, and those names might be useful data, puts them in a new column with the suffix<code>_id</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">df1</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 6 × 3</span></span>
<span><span class="co">#&gt;       x     y y_id </span></span>
<span><span class="co">#&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;chr&gt;</span></span>
<span><span class="co">#&gt; 1     1    11 a    </span></span>
<span><span class="co">#&gt; 2     1    12 b    </span></span>
<span><span class="co">#&gt; 3     2    21 a    </span></span>
<span><span class="co">#&gt; 4     2    22 b    </span></span>
<span><span class="co">#&gt; 5     3    31 a    </span></span>
<span><span class="co">#&gt; 6     3    32 b</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If you don’t want these <code>ids</code>, you can suppress this with <code>indices_include = FALSE</code>. On the other hand, it’s sometimes useful to retain the position of unnamed elements in unnamed list-columns. You can do this with <code>indices_include = TRUE</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">df2</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer</a></span><span class="op">(</span><span class="va">y</span>, indices_include <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 6 × 3</span></span>
<span><span class="co">#&gt;       x     y  y_id</span></span>
<span><span class="co">#&gt;   &lt;dbl&gt; &lt;dbl&gt; &lt;int&gt;</span></span>
<span><span class="co">#&gt; 1     1    11     1</span></span>
<span><span class="co">#&gt; 2     1    12     2</span></span>
<span><span class="co">#&gt; 3     1    13     3</span></span>
<span><span class="co">#&gt; 4     2    21     1</span></span>
<span><span class="co">#&gt; 5     3    31     1</span></span>
<span><span class="co">#&gt; 6     3    32     2</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="inconsistent-types" class="level3" data-number="25.3.3"><h3 data-number="25.3.3" class="anchored" data-anchor-id="inconsistent-types">
<span class="header-section-number">25.3.3</span> Inconsistent types</h3>
<p>What happens if you unnest a list-column contains different types of vector? For example, take the following dataset where the list-column <code>y</code> contains two numbers, a factor, and a logical, which can’t normally be mixed in a single column.</p>
<div class="cell">
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">df4</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tribble.html">tribble</a></span><span class="op">(</span></span>
<span>  <span class="op">~</span><span class="va">x</span>, <span class="op">~</span><span class="va">y</span>,</span>
<span>  <span class="st">"a"</span>, <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="fl">1</span>, <span class="st">"a"</span><span class="op">)</span>,</span>
<span>  <span class="st">"b"</span>, <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="cn">TRUE</span>, <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="st">"a"</span><span class="op">)</span>, <span class="fl">5</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer()</a></code> always keeps the set of columns change, while changing the number of rows. So what happens? How does <code><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer()</a></code> produce five rows while keeping everything in <code>y</code>?</p>
<div class="cell">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">df4</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 5 × 2</span></span>
<span><span class="co">#&gt;   x     y        </span></span>
<span><span class="co">#&gt;   &lt;chr&gt; &lt;list&gt;   </span></span>
<span><span class="co">#&gt; 1 a     &lt;dbl [1]&gt;</span></span>
<span><span class="co">#&gt; 2 a     &lt;chr [1]&gt;</span></span>
<span><span class="co">#&gt; 3 b     &lt;lgl [1]&gt;</span></span>
<span><span class="co">#&gt; 4 b     &lt;fct [1]&gt;</span></span>
<span><span class="co">#&gt; 5 b     &lt;dbl [1]&gt;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>As you can see, the output contains a list-column, but every element of the list-column contains a single element. Because <code><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer()</a></code> can’t find a common type of vector, it keeps the original types in a list-column. You might wonder if this breaks the commandment that every element of a column must be the same type — not quite, because every element is a still a list, and each component of that list contains something different.</p>
<p>What happens if you find this problem in a dataset you’re trying to rectangle? There are two basic options. You could use the <code>transform</code> argument to coerce all inputs to a common type. It’s not particularly useful here because there’s only really one class that these five class can be converted to: character.</p>
<div class="cell">
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">df4</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer</a></span><span class="op">(</span><span class="va">y</span>, transform <span class="op">=</span> <span class="va">as.character</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 5 × 2</span></span>
<span><span class="co">#&gt;   x     y    </span></span>
<span><span class="co">#&gt;   &lt;chr&gt; &lt;chr&gt;</span></span>
<span><span class="co">#&gt; 1 a     1    </span></span>
<span><span class="co">#&gt; 2 a     a    </span></span>
<span><span class="co">#&gt; 3 b     TRUE </span></span>
<span><span class="co">#&gt; 4 b     a    </span></span>
<span><span class="co">#&gt; 5 b     5</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Another option would be to filter down to the rows that have values of a specific type:</p>
<div class="cell">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">df4</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/rowwise.html">rowwise</a></span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/numeric.html">is.numeric</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 2 × 2</span></span>
<span><span class="co">#&gt; # Rowwise: </span></span>
<span><span class="co">#&gt;   x     y        </span></span>
<span><span class="co">#&gt;   &lt;chr&gt; &lt;list&gt;   </span></span>
<span><span class="co">#&gt; 1 a     &lt;dbl [1]&gt;</span></span>
<span><span class="co">#&gt; 2 b     &lt;dbl [1]&gt;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then you can call <code><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer()</a></code> once more:</p>
<div class="cell">
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">df4</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/rowwise.html">rowwise</a></span><span class="op">(</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/numeric.html">is.numeric</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer</a></span><span class="op">(</span><span class="va">y</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 2 × 2</span></span>
<span><span class="co">#&gt;   x         y</span></span>
<span><span class="co">#&gt;   &lt;chr&gt; &lt;dbl&gt;</span></span>
<span><span class="co">#&gt; 1 a         1</span></span>
<span><span class="co">#&gt; 2 b         5</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="other-functions" class="level3" data-number="25.3.4"><h3 data-number="25.3.4" class="anchored" data-anchor-id="other-functions">
<span class="header-section-number">25.3.4</span> Other functions</h3>
<p>tidyr has a few other useful rectangling functions that we’re not going to cover in this book:</p>
<ul>
<li>
<code><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_auto()</a></code> automatically picks between <code><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer()</a></code> and <code><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_wider()</a></code> based on the structure of the list-column. It’s a great for rapid exploration, but ultimately its a bad idea because it doesn’t force you to understand how your data is structured, and makes your code harder to understand.</li>
<li>
<code><a href="https://tidyr.tidyverse.org/reference/nest.html">unnest()</a></code> expands both rows and columns. It’s useful when you have a list-column that contains a 2d structure like a data frame, which we don’t see in this book.</li>
<li>
<code><a href="https://tidyr.tidyverse.org/reference/hoist.html">hoist()</a></code> allows you to reach into a deeply nested list and extract just the components that you need. It’s mostly equivalent to repeated invocations of <code><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_wider()</a></code> + <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> so read up on it if you’re trying to extract just a couple of important variables embedded in a bunch of data that you don’t care about.</li>
</ul>
<p>These are good to know about when you’re other people’s code and for tackling rarer rectangling challenges.</p>
</section><section id="exercises" class="level3" data-number="25.3.5"><h3 data-number="25.3.5" class="anchored" data-anchor-id="exercises">
<span class="header-section-number">25.3.5</span> Exercises</h3>
<ol type="1">
<li>
<p>From time-to-time you encounter data frames with multiple list-columns with aligned values. For example, in the following data frame, the values of <code>y</code> and <code>z</code> are aligned (i.e.&nbsp;<code>y</code> and <code>z</code> will always have the same length within a row, and the first value of <code>y</code> corresponds to the first value of <code>z</code>). What happens if you apply two <code><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer()</a></code> calls to this data frame? How can you preserve the relationship between <code>x</code> and <code>y</code>? (Hint: carefully read the docs).</p>
<div class="cell">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">df4</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tribble.html">tribble</a></span><span class="op">(</span></span>
<span>  <span class="op">~</span><span class="va">x</span>, <span class="op">~</span><span class="va">y</span>, <span class="op">~</span><span class="va">z</span>,</span>
<span>  <span class="st">"a"</span>, <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="st">"y-a-1"</span>, <span class="st">"y-a-2"</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="st">"z-a-1"</span>, <span class="st">"z-a-2"</span><span class="op">)</span>,</span>
<span>  <span class="st">"b"</span>, <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="st">"y-b-1"</span>, <span class="st">"y-b-2"</span>, <span class="st">"y-b-3"</span><span class="op">)</span>, <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="st">"z-b-1"</span>, <span class="st">"z-b-2"</span>, <span class="st">"z-b-3"</span><span class="op">)</span></span>
<span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</li>
</ol></section></section><section id="case-studies" class="level2" data-number="25.4"><h2 data-number="25.4" class="anchored" data-anchor-id="case-studies">
<span class="header-section-number">25.4</span> Case studies</h2>
<p>So far you’ve learned about the simplest case of list-columns, where rectangling only requires a single call to <code><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer()</a></code> or <code><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_wider()</a></code>. The main difference between real data and these simple examples is that real data typically containsmultiple levels of nesting that requires multiple calls to <code><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer()</a></code> and <code><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_wider()</a></code>. This section will work through four real rectangling challenges using datasets from the repurrrsive package that are inspired by datasets that we’ve encountered in the wild.</p>
<section id="very-wide-data" class="level3" data-number="25.4.1"><h3 data-number="25.4.1" class="anchored" data-anchor-id="very-wide-data">
<span class="header-section-number">25.4.1</span> Very wide data</h3>
<p>We’ll start by exploring <code>gh_repos</code>. This is a list that contains data about a collection of GitHub repositories retrieved using the GitHub API. It’s a very deeply nested list so it’s difficult to show the structure in this book; you might want to explore a little on your own with <code>View(gh_repos)</code> before we continue.</p>
<p><code>gh_repos</code> is a list, but our tools work with list-columns, so we’ll begin by putting it into a tibble. We call the column <code>json</code> for reasons we’ll get to later.</p>
<div class="cell">
<div class="sourceCode" id="cb27"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">repos</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>json <span class="op">=</span> <span class="va">gh_repos</span><span class="op">)</span></span>
<span><span class="va">repos</span></span>
<span><span class="co">#&gt; # A tibble: 6 × 1</span></span>
<span><span class="co">#&gt;   json       </span></span>
<span><span class="co">#&gt;   &lt;list&gt;     </span></span>
<span><span class="co">#&gt; 1 &lt;list [30]&gt;</span></span>
<span><span class="co">#&gt; 2 &lt;list [30]&gt;</span></span>
<span><span class="co">#&gt; 3 &lt;list [30]&gt;</span></span>
<span><span class="co">#&gt; 4 &lt;list [26]&gt;</span></span>
<span><span class="co">#&gt; 5 &lt;list [30]&gt;</span></span>
<span><span class="co">#&gt; 6 &lt;list [30]&gt;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This tibble contains 6 rows, one row for each child of <code>gh_repos</code>. Each row contains a unnamed list with either 26 or 30 rows. Since these are unnamed, we’ll start with an <code><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer()</a></code> to put each child in its own row:</p>
<div class="cell">
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">repos</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer</a></span><span class="op">(</span><span class="va">json</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 176 × 1</span></span>
<span><span class="co">#&gt;   json             </span></span>
<span><span class="co">#&gt;   &lt;list&gt;           </span></span>
<span><span class="co">#&gt; 1 &lt;named list [68]&gt;</span></span>
<span><span class="co">#&gt; 2 &lt;named list [68]&gt;</span></span>
<span><span class="co">#&gt; 3 &lt;named list [68]&gt;</span></span>
<span><span class="co">#&gt; 4 &lt;named list [68]&gt;</span></span>
<span><span class="co">#&gt; 5 &lt;named list [68]&gt;</span></span>
<span><span class="co">#&gt; 6 &lt;named list [68]&gt;</span></span>
<span><span class="co">#&gt; # … with 170 more rows</span></span>
<span><span class="co">#&gt; # ℹ Use `print(n = ...)` to see more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>At first glance, it might seem like we haven’t improved the situation: while we have more rows (176 instead of 6) each element of <code>json</code> is still a list. However, there’s an important difference: now each element is a <strong>named</strong> list so we can use <code>unnamed_wider()</code> to put each element into its own column:</p>
<div class="cell">
<div class="sourceCode" id="cb29"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">repos</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer</a></span><span class="op">(</span><span class="va">json</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_wider</a></span><span class="op">(</span><span class="va">json</span><span class="op">)</span> </span>
<span><span class="co">#&gt; # A tibble: 176 × 68</span></span>
<span><span class="co">#&gt;        id name  full_…¹ owner        private html_…² descr…³ fork  url   forks…⁴</span></span>
<span><span class="co">#&gt;     &lt;int&gt; &lt;chr&gt; &lt;chr&gt;   &lt;list&gt;       &lt;lgl&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;lgl&gt; &lt;chr&gt; &lt;chr&gt;  </span></span>
<span><span class="co">#&gt; 1  6.12e7 after gaborc… &lt;named list&gt; FALSE   https:… Run Co… FALSE http… https:…</span></span>
<span><span class="co">#&gt; 2  4.05e7 argu… gaborc… &lt;named list&gt; FALSE   https:… Declar… FALSE http… https:…</span></span>
<span><span class="co">#&gt; 3  3.64e7 ask   gaborc… &lt;named list&gt; FALSE   https:… Friend… FALSE http… https:…</span></span>
<span><span class="co">#&gt; 4  3.49e7 base… gaborc… &lt;named list&gt; FALSE   https:… Do we … FALSE http… https:…</span></span>
<span><span class="co">#&gt; 5  6.16e7 cite… gaborc… &lt;named list&gt; FALSE   https:… Test R… TRUE  http… https:…</span></span>
<span><span class="co">#&gt; 6  3.39e7 clis… gaborc… &lt;named list&gt; FALSE   https:… Unicod… FALSE http… https:…</span></span>
<span><span class="co">#&gt; # … with 170 more rows, 58 more variables: keys_url &lt;chr&gt;,</span></span>
<span><span class="co">#&gt; #   collaborators_url &lt;chr&gt;, teams_url &lt;chr&gt;, hooks_url &lt;chr&gt;,</span></span>
<span><span class="co">#&gt; #   issue_events_url &lt;chr&gt;, events_url &lt;chr&gt;, assignees_url &lt;chr&gt;,</span></span>
<span><span class="co">#&gt; #   branches_url &lt;chr&gt;, tags_url &lt;chr&gt;, blobs_url &lt;chr&gt;, git_tags_url &lt;chr&gt;,</span></span>
<span><span class="co">#&gt; #   git_refs_url &lt;chr&gt;, trees_url &lt;chr&gt;, statuses_url &lt;chr&gt;,</span></span>
<span><span class="co">#&gt; #   languages_url &lt;chr&gt;, stargazers_url &lt;chr&gt;, contributors_url &lt;chr&gt;,</span></span>
<span><span class="co">#&gt; #   subscribers_url &lt;chr&gt;, subscription_url &lt;chr&gt;, commits_url &lt;chr&gt;, …</span></span>
<span><span class="co">#&gt; # ℹ Use `print(n = ...)` to see more rows, and `colnames()` to see all variable names</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This has worked but the result is a little overwhelming: there are so many columns that tibble doesn’t even print all of them! We can see them all with <code><a href="https://rdrr.io/r/base/names.html">names()</a></code>:</p>
<div class="cell">
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">repos</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer</a></span><span class="op">(</span><span class="va">json</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_wider</a></span><span class="op">(</span><span class="va">json</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://rdrr.io/r/base/names.html">names</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt;  [1] "id"                "name"              "full_name"        </span></span>
<span><span class="co">#&gt;  [4] "owner"             "private"           "html_url"         </span></span>
<span><span class="co">#&gt;  [7] "description"       "fork"              "url"              </span></span>
<span><span class="co">#&gt; [10] "forks_url"         "keys_url"          "collaborators_url"</span></span>
<span><span class="co">#&gt; [13] "teams_url"         "hooks_url"         "issue_events_url" </span></span>
<span><span class="co">#&gt; [16] "events_url"        "assignees_url"     "branches_url"     </span></span>
<span><span class="co">#&gt; [19] "tags_url"          "blobs_url"         "git_tags_url"     </span></span>
<span><span class="co">#&gt; [22] "git_refs_url"      "trees_url"         "statuses_url"     </span></span>
<span><span class="co">#&gt; [25] "languages_url"     "stargazers_url"    "contributors_url" </span></span>
<span><span class="co">#&gt; [28] "subscribers_url"   "subscription_url"  "commits_url"      </span></span>
<span><span class="co">#&gt; [31] "git_commits_url"   "comments_url"      "issue_comment_url"</span></span>
<span><span class="co">#&gt; [34] "contents_url"      "compare_url"       "merges_url"       </span></span>
<span><span class="co">#&gt; [37] "archive_url"       "downloads_url"     "issues_url"       </span></span>
<span><span class="co">#&gt; [40] "pulls_url"         "milestones_url"    "notifications_url"</span></span>
<span><span class="co">#&gt; [43] "labels_url"        "releases_url"      "deployments_url"  </span></span>
<span><span class="co">#&gt; [46] "created_at"        "updated_at"        "pushed_at"        </span></span>
<span><span class="co">#&gt; [49] "git_url"           "ssh_url"           "clone_url"        </span></span>
<span><span class="co">#&gt; [52] "svn_url"           "homepage"          "size"             </span></span>
<span><span class="co">#&gt; [55] "stargazers_count"  "watchers_count"    "language"         </span></span>
<span><span class="co">#&gt; [58] "has_issues"        "has_downloads"     "has_wiki"         </span></span>
<span><span class="co">#&gt; [61] "has_pages"         "forks_count"       "mirror_url"       </span></span>
<span><span class="co">#&gt; [64] "open_issues_count" "forks"             "open_issues"      </span></span>
<span><span class="co">#&gt; [67] "watchers"          "default_branch"</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Let’s select a few that look interesting:</p>
<div class="cell">
<div class="sourceCode" id="cb31"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">repos</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer</a></span><span class="op">(</span><span class="va">json</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_wider</a></span><span class="op">(</span><span class="va">json</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">id</span>, <span class="va">full_name</span>, <span class="va">owner</span>, <span class="va">description</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 176 × 4</span></span>
<span><span class="co">#&gt;         id full_name               owner             description                </span></span>
<span><span class="co">#&gt;      &lt;int&gt; &lt;chr&gt;                   &lt;list&gt;            &lt;chr&gt;                      </span></span>
<span><span class="co">#&gt; 1 61160198 gaborcsardi/after       &lt;named list [17]&gt; Run Code in the Background </span></span>
<span><span class="co">#&gt; 2 40500181 gaborcsardi/argufy      &lt;named list [17]&gt; Declarative function argum…</span></span>
<span><span class="co">#&gt; 3 36442442 gaborcsardi/ask         &lt;named list [17]&gt; Friendly CLI interaction i…</span></span>
<span><span class="co">#&gt; 4 34924886 gaborcsardi/baseimports &lt;named list [17]&gt; Do we get warnings for und…</span></span>
<span><span class="co">#&gt; 5 61620661 gaborcsardi/citest      &lt;named list [17]&gt; Test R package and repo fo…</span></span>
<span><span class="co">#&gt; 6 33907457 gaborcsardi/clisymbols  &lt;named list [17]&gt; Unicode symbols for CLI ap…</span></span>
<span><span class="co">#&gt; # … with 170 more rows</span></span>
<span><span class="co">#&gt; # ℹ Use `print(n = ...)` to see more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You can use this to work back to understand how <code>gh_repos</code> was strucured: each child was a GitHub user containing a list of up to 30 GitHub repositories that they created.</p>
<p><code>owner</code> is another list-column, and since it a contains a named list, we can use <code><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_wider()</a></code> to get at the values:</p>
<div class="cell">
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">repos</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer</a></span><span class="op">(</span><span class="va">json</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_wider</a></span><span class="op">(</span><span class="va">json</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">id</span>, <span class="va">full_name</span>, <span class="va">owner</span>, <span class="va">description</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_wider</a></span><span class="op">(</span><span class="va">owner</span><span class="op">)</span></span>
<span><span class="co">#&gt; Error in `unpack()`:</span></span>
<span><span class="co">#&gt; ! Names must be unique.</span></span>
<span><span class="co">#&gt; ✖ These names are duplicated:</span></span>
<span><span class="co">#&gt;   * "id" at locations 1 and 4.</span></span>
<span><span class="co">#&gt; ℹ Use argument `names_repair` to specify repair strategy.</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Uh oh, this list column also contains an <code>id</code> column and we can’t have two <code>id</code> columns in the same data frame. Rather than following the advice to use <code>names_repair</code> (which would also work), we’ll instead use <code>names_sep</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">repos</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer</a></span><span class="op">(</span><span class="va">json</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_wider</a></span><span class="op">(</span><span class="va">json</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">id</span>, <span class="va">full_name</span>, <span class="va">owner</span>, <span class="va">description</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_wider</a></span><span class="op">(</span><span class="va">owner</span>, names_sep <span class="op">=</span> <span class="st">"_"</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 176 × 20</span></span>
<span><span class="co">#&gt;       id full_…¹ owner…² owner…³ owner…⁴ owner…⁵ owner…⁶ owner…⁷ owner…⁸ owner…⁹</span></span>
<span><span class="co">#&gt;    &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;     &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;   &lt;chr&gt;  </span></span>
<span><span class="co">#&gt; 1 6.12e7 gaborc… gaborc…  660288 https:… ""      https:… https:… https:… https:…</span></span>
<span><span class="co">#&gt; 2 4.05e7 gaborc… gaborc…  660288 https:… ""      https:… https:… https:… https:…</span></span>
<span><span class="co">#&gt; 3 3.64e7 gaborc… gaborc…  660288 https:… ""      https:… https:… https:… https:…</span></span>
<span><span class="co">#&gt; 4 3.49e7 gaborc… gaborc…  660288 https:… ""      https:… https:… https:… https:…</span></span>
<span><span class="co">#&gt; 5 6.16e7 gaborc… gaborc…  660288 https:… ""      https:… https:… https:… https:…</span></span>
<span><span class="co">#&gt; 6 3.39e7 gaborc… gaborc…  660288 https:… ""      https:… https:… https:… https:…</span></span>
<span><span class="co">#&gt; # … with 170 more rows, 10 more variables: owner_gists_url &lt;chr&gt;,</span></span>
<span><span class="co">#&gt; #   owner_starred_url &lt;chr&gt;, owner_subscriptions_url &lt;chr&gt;,</span></span>
<span><span class="co">#&gt; #   owner_organizations_url &lt;chr&gt;, owner_repos_url &lt;chr&gt;,</span></span>
<span><span class="co">#&gt; #   owner_events_url &lt;chr&gt;, owner_received_events_url &lt;chr&gt;, owner_type &lt;chr&gt;,</span></span>
<span><span class="co">#&gt; #   owner_site_admin &lt;lgl&gt;, description &lt;chr&gt;, and abbreviated variable names</span></span>
<span><span class="co">#&gt; #   ¹​full_name, ²​owner_login, ³​owner_id, ⁴​owner_avatar_url, ⁵​owner_gravatar_id,</span></span>
<span><span class="co">#&gt; #   ⁶​owner_url, ⁷​owner_html_url, ⁸​owner_followers_url, ⁹​owner_following_url</span></span>
<span><span class="co">#&gt; # ℹ Use `print(n = ...)` to see more rows, and `colnames()` to see all variable names</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This gives another wide dataset, but you can see that <code>owner</code> appears to contain a lot of additional data about the person who “owns” the repository.</p>
</section><section id="relational-data" class="level3" data-number="25.4.2"><h3 data-number="25.4.2" class="anchored" data-anchor-id="relational-data">
<span class="header-section-number">25.4.2</span> Relational data</h3>
<p>Nested data is sometimes used to represent data that we’d usually spread out into multiple data frames. For example, take <code>got_chars</code>. Like <code>gh_repos</code> it’s a list, so we start by turning it into a list-column of a tibble:</p>
<div class="cell">
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">chars</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>json <span class="op">=</span> <span class="va">got_chars</span><span class="op">)</span></span>
<span><span class="va">chars</span></span>
<span><span class="co">#&gt; # A tibble: 30 × 1</span></span>
<span><span class="co">#&gt;   json             </span></span>
<span><span class="co">#&gt;   &lt;list&gt;           </span></span>
<span><span class="co">#&gt; 1 &lt;named list [18]&gt;</span></span>
<span><span class="co">#&gt; 2 &lt;named list [18]&gt;</span></span>
<span><span class="co">#&gt; 3 &lt;named list [18]&gt;</span></span>
<span><span class="co">#&gt; 4 &lt;named list [18]&gt;</span></span>
<span><span class="co">#&gt; 5 &lt;named list [18]&gt;</span></span>
<span><span class="co">#&gt; 6 &lt;named list [18]&gt;</span></span>
<span><span class="co">#&gt; # … with 24 more rows</span></span>
<span><span class="co">#&gt; # ℹ Use `print(n = ...)` to see more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code>json</code> column contains named values, so we’ll start by widening it:</p>
<div class="cell">
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">chars</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_wider</a></span><span class="op">(</span><span class="va">json</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 30 × 18</span></span>
<span><span class="co">#&gt;   url            id name  gender culture born  died  alive titles aliases father</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;       &lt;int&gt; &lt;chr&gt; &lt;chr&gt;  &lt;chr&gt;   &lt;chr&gt; &lt;chr&gt; &lt;lgl&gt; &lt;list&gt; &lt;list&gt;  &lt;chr&gt; </span></span>
<span><span class="co">#&gt; 1 https://ww…  1022 Theo… Male   "Ironb… "In … ""    TRUE  &lt;chr&gt;  &lt;chr&gt;   ""    </span></span>
<span><span class="co">#&gt; 2 https://ww…  1052 Tyri… Male   ""      "In … ""    TRUE  &lt;chr&gt;  &lt;chr&gt;   ""    </span></span>
<span><span class="co">#&gt; 3 https://ww…  1074 Vict… Male   "Ironb… "In … ""    TRUE  &lt;chr&gt;  &lt;chr&gt;   ""    </span></span>
<span><span class="co">#&gt; 4 https://ww…  1109 Will  Male   ""      ""    "In … FALSE &lt;chr&gt;  &lt;chr&gt;   ""    </span></span>
<span><span class="co">#&gt; 5 https://ww…  1166 Areo… Male   "Norvo… "In … ""    TRUE  &lt;chr&gt;  &lt;chr&gt;   ""    </span></span>
<span><span class="co">#&gt; 6 https://ww…  1267 Chett Male   ""      "At … "In … FALSE &lt;chr&gt;  &lt;chr&gt;   ""    </span></span>
<span><span class="co">#&gt; # … with 24 more rows, and 7 more variables: mother &lt;chr&gt;, spouse &lt;chr&gt;,</span></span>
<span><span class="co">#&gt; #   allegiances &lt;list&gt;, books &lt;list&gt;, povBooks &lt;list&gt;, tvSeries &lt;list&gt;,</span></span>
<span><span class="co">#&gt; #   playedBy &lt;list&gt;</span></span>
<span><span class="co">#&gt; # ℹ Use `print(n = ...)` to see more rows, and `colnames()` to see all variable names</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And selecting a few columns just to make it easier to read:</p>
<div class="cell">
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">characters</span> <span class="op">&lt;-</span> <span class="va">chars</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_wider</a></span><span class="op">(</span><span class="va">json</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">id</span>, <span class="va">name</span>, <span class="va">gender</span>, <span class="va">culture</span>, <span class="va">born</span>, <span class="va">died</span>, <span class="va">alive</span><span class="op">)</span></span>
<span><span class="va">characters</span></span>
<span><span class="co">#&gt; # A tibble: 30 × 7</span></span>
<span><span class="co">#&gt;      id name              gender culture    born                     died  alive</span></span>
<span><span class="co">#&gt;   &lt;int&gt; &lt;chr&gt;             &lt;chr&gt;  &lt;chr&gt;      &lt;chr&gt;                    &lt;chr&gt; &lt;lgl&gt;</span></span>
<span><span class="co">#&gt; 1  1022 Theon Greyjoy     Male   "Ironborn" "In 278 AC or 279 AC, a… ""    TRUE </span></span>
<span><span class="co">#&gt; 2  1052 Tyrion Lannister  Male   ""         "In 273 AC, at Casterly… ""    TRUE </span></span>
<span><span class="co">#&gt; 3  1074 Victarion Greyjoy Male   "Ironborn" "In 268 AC or before, a… ""    TRUE </span></span>
<span><span class="co">#&gt; 4  1109 Will              Male   ""         ""                       "In … FALSE</span></span>
<span><span class="co">#&gt; 5  1166 Areo Hotah        Male   "Norvoshi" "In 257 AC or before, a… ""    TRUE </span></span>
<span><span class="co">#&gt; 6  1267 Chett             Male   ""         "At Hag's Mire"          "In … FALSE</span></span>
<span><span class="co">#&gt; # … with 24 more rows</span></span>
<span><span class="co">#&gt; # ℹ Use `print(n = ...)` to see more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>There are also many list-columns:</p>
<div class="cell">
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">chars</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_wider</a></span><span class="op">(</span><span class="va">json</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">id</span>, <span class="fu">where</span><span class="op">(</span><span class="va">is.list</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 30 × 8</span></span>
<span><span class="co">#&gt;      id titles    aliases    allegiances books     povBooks  tvSeries  playedBy </span></span>
<span><span class="co">#&gt;   &lt;int&gt; &lt;list&gt;    &lt;list&gt;     &lt;list&gt;      &lt;list&gt;    &lt;list&gt;    &lt;list&gt;    &lt;list&gt;   </span></span>
<span><span class="co">#&gt; 1  1022 &lt;chr [3]&gt; &lt;chr [4]&gt;  &lt;chr [1]&gt;   &lt;chr [3]&gt; &lt;chr [2]&gt; &lt;chr [6]&gt; &lt;chr [1]&gt;</span></span>
<span><span class="co">#&gt; 2  1052 &lt;chr [2]&gt; &lt;chr [11]&gt; &lt;chr [1]&gt;   &lt;chr [2]&gt; &lt;chr [4]&gt; &lt;chr [6]&gt; &lt;chr [1]&gt;</span></span>
<span><span class="co">#&gt; 3  1074 &lt;chr [2]&gt; &lt;chr [1]&gt;  &lt;chr [1]&gt;   &lt;chr [3]&gt; &lt;chr [2]&gt; &lt;chr [1]&gt; &lt;chr [1]&gt;</span></span>
<span><span class="co">#&gt; 4  1109 &lt;chr [1]&gt; &lt;chr [1]&gt;  &lt;NULL&gt;      &lt;chr [1]&gt; &lt;chr [1]&gt; &lt;chr [1]&gt; &lt;chr [1]&gt;</span></span>
<span><span class="co">#&gt; 5  1166 &lt;chr [1]&gt; &lt;chr [1]&gt;  &lt;chr [1]&gt;   &lt;chr [3]&gt; &lt;chr [2]&gt; &lt;chr [2]&gt; &lt;chr [1]&gt;</span></span>
<span><span class="co">#&gt; 6  1267 &lt;chr [1]&gt; &lt;chr [1]&gt;  &lt;NULL&gt;      &lt;chr [2]&gt; &lt;chr [1]&gt; &lt;chr [1]&gt; &lt;chr [1]&gt;</span></span>
<span><span class="co">#&gt; # … with 24 more rows</span></span>
<span><span class="co">#&gt; # ℹ Use `print(n = ...)` to see more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Lets explore the <code>titles</code> column. It’s an unnamed list-column, so we’ll unnest it into rows:</p>
<div class="cell">
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">chars</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_wider</a></span><span class="op">(</span><span class="va">json</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">id</span>, <span class="va">titles</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer</a></span><span class="op">(</span><span class="va">titles</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 60 × 2</span></span>
<span><span class="co">#&gt;      id titles                                              </span></span>
<span><span class="co">#&gt;   &lt;int&gt; &lt;chr&gt;                                               </span></span>
<span><span class="co">#&gt; 1  1022 Prince of Winterfell                                </span></span>
<span><span class="co">#&gt; 2  1022 Captain of Sea Bitch                                </span></span>
<span><span class="co">#&gt; 3  1022 Lord of the Iron Islands (by law of the green lands)</span></span>
<span><span class="co">#&gt; 4  1052 Acting Hand of the King (former)                    </span></span>
<span><span class="co">#&gt; 5  1052 Master of Coin (former)                             </span></span>
<span><span class="co">#&gt; 6  1074 Lord Captain of the Iron Fleet                      </span></span>
<span><span class="co">#&gt; # … with 54 more rows</span></span>
<span><span class="co">#&gt; # ℹ Use `print(n = ...)` to see more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You might expect to see this data in its own table because it would be easy to join to the characters data as needed. To do so, we’ll do a little cleaning: removing the rows containing empty strings and renaming <code>titles</code> to <code>title</code> since each row now only contains a single title.</p>
<div class="cell">
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">titles</span> <span class="op">&lt;-</span> <span class="va">chars</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_wider</a></span><span class="op">(</span><span class="va">json</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">id</span>, <span class="va">titles</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer</a></span><span class="op">(</span><span class="va">titles</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">titles</span> <span class="op">!=</span> <span class="st">""</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/rename.html">rename</a></span><span class="op">(</span>title <span class="op">=</span> <span class="va">titles</span><span class="op">)</span></span>
<span><span class="va">titles</span></span>
<span><span class="co">#&gt; # A tibble: 53 × 2</span></span>
<span><span class="co">#&gt;      id title                                               </span></span>
<span><span class="co">#&gt;   &lt;int&gt; &lt;chr&gt;                                               </span></span>
<span><span class="co">#&gt; 1  1022 Prince of Winterfell                                </span></span>
<span><span class="co">#&gt; 2  1022 Captain of Sea Bitch                                </span></span>
<span><span class="co">#&gt; 3  1022 Lord of the Iron Islands (by law of the green lands)</span></span>
<span><span class="co">#&gt; 4  1052 Acting Hand of the King (former)                    </span></span>
<span><span class="co">#&gt; 5  1052 Master of Coin (former)                             </span></span>
<span><span class="co">#&gt; 6  1074 Lord Captain of the Iron Fleet                      </span></span>
<span><span class="co">#&gt; # … with 47 more rows</span></span>
<span><span class="co">#&gt; # ℹ Use `print(n = ...)` to see more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now, for example, we could use this table to all the characters that are captains and see all their titles:</p>
<div class="cell">
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">captains</span> <span class="op">&lt;-</span> <span class="va">titles</span> <span class="op">|&gt;</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="fu"><a href="https://stringr.tidyverse.org/reference/str_detect.html">str_detect</a></span><span class="op">(</span><span class="va">title</span>, <span class="st">"Captain"</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">captains</span></span>
<span><span class="co">#&gt; # A tibble: 5 × 2</span></span>
<span><span class="co">#&gt;      id title                                 </span></span>
<span><span class="co">#&gt;   &lt;int&gt; &lt;chr&gt;                                 </span></span>
<span><span class="co">#&gt; 1  1022 Captain of Sea Bitch                  </span></span>
<span><span class="co">#&gt; 2  1074 Lord Captain of the Iron Fleet        </span></span>
<span><span class="co">#&gt; 3  1166 Captain of the Guard at Sunspear      </span></span>
<span><span class="co">#&gt; 4   150 Captain of the Black Wind             </span></span>
<span><span class="co">#&gt; 5    60 Captain of the Golden Storm (formerly)</span></span>
<span></span>
<span><span class="va">characters</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter-joins.html">semi_join</a></span><span class="op">(</span><span class="va">captains</span>, by <span class="op">=</span> <span class="st">"id"</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">id</span>, <span class="va">name</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">titles</span>, by <span class="op">=</span> <span class="st">"id"</span>, multiple <span class="op">=</span> <span class="st">"all"</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 11 × 3</span></span>
<span><span class="co">#&gt;      id name              title                                               </span></span>
<span><span class="co">#&gt;   &lt;int&gt; &lt;chr&gt;             &lt;chr&gt;                                               </span></span>
<span><span class="co">#&gt; 1  1022 Theon Greyjoy     Prince of Winterfell                                </span></span>
<span><span class="co">#&gt; 2  1022 Theon Greyjoy     Captain of Sea Bitch                                </span></span>
<span><span class="co">#&gt; 3  1022 Theon Greyjoy     Lord of the Iron Islands (by law of the green lands)</span></span>
<span><span class="co">#&gt; 4  1074 Victarion Greyjoy Lord Captain of the Iron Fleet                      </span></span>
<span><span class="co">#&gt; 5  1074 Victarion Greyjoy Master of the Iron Victory                          </span></span>
<span><span class="co">#&gt; 6  1166 Areo Hotah        Captain of the Guard at Sunspear                    </span></span>
<span><span class="co">#&gt; # … with 5 more rows</span></span>
<span><span class="co">#&gt; # ℹ Use `print(n = ...)` to see more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>You could imagine creating a table like this for each of the list-columns, then using joins to combine them with the character data as you need it.</p>
</section><section id="a-dash-of-text-analysis" class="level3" data-number="25.4.3"><h3 data-number="25.4.3" class="anchored" data-anchor-id="a-dash-of-text-analysis">
<span class="header-section-number">25.4.3</span> A dash of text analysis</h3>
<p>What if we wanted to find the most common words in the title? One simple approach starts by using <code><a href="https://stringr.tidyverse.org/reference/str_split.html">str_split()</a></code> to break each element of <code>title</code> up into words by spitting on <code>" "</code>:</p>
<div class="cell">
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">titles</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>word <span class="op">=</span> <span class="fu"><a href="https://stringr.tidyverse.org/reference/str_split.html">str_split</a></span><span class="op">(</span><span class="va">title</span>, <span class="st">" "</span><span class="op">)</span>, .keep <span class="op">=</span> <span class="st">"unused"</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 53 × 2</span></span>
<span><span class="co">#&gt;      id word      </span></span>
<span><span class="co">#&gt;   &lt;int&gt; &lt;list&gt;    </span></span>
<span><span class="co">#&gt; 1  1022 &lt;chr [3]&gt; </span></span>
<span><span class="co">#&gt; 2  1022 &lt;chr [4]&gt; </span></span>
<span><span class="co">#&gt; 3  1022 &lt;chr [11]&gt;</span></span>
<span><span class="co">#&gt; 4  1052 &lt;chr [6]&gt; </span></span>
<span><span class="co">#&gt; 5  1052 &lt;chr [4]&gt; </span></span>
<span><span class="co">#&gt; 6  1074 &lt;chr [6]&gt; </span></span>
<span><span class="co">#&gt; # … with 47 more rows</span></span>
<span><span class="co">#&gt; # ℹ Use `print(n = ...)` to see more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This creates a unnamed variable length list-column, so we can use <code><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer()</a></code>:</p>
<div class="cell">
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">titles</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>word <span class="op">=</span> <span class="fu"><a href="https://stringr.tidyverse.org/reference/str_split.html">str_split</a></span><span class="op">(</span><span class="va">title</span>, <span class="st">" "</span><span class="op">)</span>, .keep <span class="op">=</span> <span class="st">"unused"</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer</a></span><span class="op">(</span><span class="va">word</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 202 × 2</span></span>
<span><span class="co">#&gt;      id word      </span></span>
<span><span class="co">#&gt;   &lt;int&gt; &lt;chr&gt;     </span></span>
<span><span class="co">#&gt; 1  1022 Prince    </span></span>
<span><span class="co">#&gt; 2  1022 of        </span></span>
<span><span class="co">#&gt; 3  1022 Winterfell</span></span>
<span><span class="co">#&gt; 4  1022 Captain   </span></span>
<span><span class="co">#&gt; 5  1022 of        </span></span>
<span><span class="co">#&gt; 6  1022 Sea       </span></span>
<span><span class="co">#&gt; # … with 196 more rows</span></span>
<span><span class="co">#&gt; # ℹ Use `print(n = ...)` to see more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>And then we can count that column to find the most common:</p>
<div class="cell">
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">titles</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>word <span class="op">=</span> <span class="fu"><a href="https://stringr.tidyverse.org/reference/str_split.html">str_split</a></span><span class="op">(</span><span class="va">title</span>, <span class="st">" "</span><span class="op">)</span>, .keep <span class="op">=</span> <span class="st">"unused"</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer</a></span><span class="op">(</span><span class="va">word</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">word</span>, sort <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 78 × 2</span></span>
<span><span class="co">#&gt;   word        n</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;   &lt;int&gt;</span></span>
<span><span class="co">#&gt; 1 of         41</span></span>
<span><span class="co">#&gt; 2 the        29</span></span>
<span><span class="co">#&gt; 3 Lord        9</span></span>
<span><span class="co">#&gt; 4 Hand        6</span></span>
<span><span class="co">#&gt; 5 Captain     5</span></span>
<span><span class="co">#&gt; 6 King        5</span></span>
<span><span class="co">#&gt; # … with 72 more rows</span></span>
<span><span class="co">#&gt; # ℹ Use `print(n = ...)` to see more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Some of those words are not very interesting so we could create a list of common words to drop. In text analysis these is commonly called stop words.</p>
<div class="cell">
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">stop_words</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>word <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"of"</span>, <span class="st">"the"</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="va">titles</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>word <span class="op">=</span> <span class="fu"><a href="https://stringr.tidyverse.org/reference/str_split.html">str_split</a></span><span class="op">(</span><span class="va">title</span>, <span class="st">" "</span><span class="op">)</span>, .keep <span class="op">=</span> <span class="st">"unused"</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer</a></span><span class="op">(</span><span class="va">word</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter-joins.html">anti_join</a></span><span class="op">(</span><span class="va">stop_words</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">word</span>, sort <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span><span class="co">#&gt; Joining, by = "word"</span></span>
<span><span class="co">#&gt; # A tibble: 76 × 2</span></span>
<span><span class="co">#&gt;   word         n</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;    &lt;int&gt;</span></span>
<span><span class="co">#&gt; 1 Lord         9</span></span>
<span><span class="co">#&gt; 2 Hand         6</span></span>
<span><span class="co">#&gt; 3 Captain      5</span></span>
<span><span class="co">#&gt; 4 King         5</span></span>
<span><span class="co">#&gt; 5 Princess     5</span></span>
<span><span class="co">#&gt; 6 Queen        5</span></span>
<span><span class="co">#&gt; # … with 70 more rows</span></span>
<span><span class="co">#&gt; # ℹ Use `print(n = ...)` to see more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Breaking up text into individual fragments is a powerful idea that underlies much of text analysis. If this sounds interesting, a good place to learn more is <a href="https://www.tidytextmining.com">Text Mining with R</a> by Julia Silge and David Robinson.</p>
</section><section id="deeply-nested" class="level3" data-number="25.4.4"><h3 data-number="25.4.4" class="anchored" data-anchor-id="deeply-nested">
<span class="header-section-number">25.4.4</span> Deeply nested</h3>
<p>We’ll finish off these case studies with a list-column that’s very deeply nested and requires repeated rounds of <code><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_wider()</a></code> and <code><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer()</a></code> to unravel: <code>gmaps_cities</code>. This is a two column tibble containing five city names and the results of using Google’s <a href="https://developers.google.com/maps/documentation/geocoding">geocoding API</a> to determine their location:</p>
<div class="cell">
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># gmaps_cities</span></span>
<span><span class="co">#&gt; # A tibble: 5 × 2</span></span>
<span><span class="co">#&gt;   city       json            </span></span>
<span><span class="co">#&gt;   &lt;chr&gt;      &lt;list&gt;          </span></span>
<span><span class="co">#&gt; 1 Houston    &lt;named list [2]&gt;</span></span>
<span><span class="co">#&gt; 2 Washington &lt;named list [2]&gt;</span></span>
<span><span class="co">#&gt; 3 New York   &lt;named list [2]&gt;</span></span>
<span><span class="co">#&gt; 4 Chicago    &lt;named list [2]&gt;</span></span>
<span><span class="co">#&gt; 5 Arlington  &lt;named list [2]&gt;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p><code>json</code> is a list-column with internal names, so we start with an <code><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_wider()</a></code>:</p>
<div class="cell">
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># gmaps_cities |&gt; </span></span>
<span><span class="co">#   unnest_wider(json)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>This gives us the <code>status</code> and the <code>results</code>. We’ll drop the status column since they’re all <code>OK</code>; in a real analysis, you’d also want capture all the rows where <code>status != "OK"</code> and figure out what went wrong. <code>results</code> is an unnamed list, with either one or two elements (we’ll see why shortly) so we’ll unnest it into rows:</p>
<div class="cell">
<div class="sourceCode" id="cb47"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># gmaps_cities |&gt; </span></span>
<span><span class="co">#   unnest_wider(json) |&gt; </span></span>
<span><span class="co">#   select(-status) |&gt; </span></span>
<span><span class="co">#   unnest_longer(results)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now <code>results</code> is a named list, so we’ll use <code><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_wider()</a></code>:</p>
<div class="cell">
<div class="sourceCode" id="cb48"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># locations &lt;- gmaps_cities |&gt; </span></span>
<span><span class="co">#   unnest_wider(json) |&gt; </span></span>
<span><span class="co">#   select(-status) |&gt; </span></span>
<span><span class="co">#   unnest_longer(results) |&gt; </span></span>
<span><span class="co">#   unnest_wider(results)</span></span>
<span><span class="co"># locations</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now we can see why two cities got two results: Washington matched both Washington state and Washington, DC, and Arlington matched Arlington, Virginia and Arlington, Texas.</p>
<p>There are few different places we could go from here. We might want to determine the exact location of the match, which is stored in the <code>geometry</code> list-column:</p>
<div class="cell">
<div class="sourceCode" id="cb49"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># locations |&gt; </span></span>
<span><span class="co">#   select(city, formatted_address, geometry) |&gt; </span></span>
<span><span class="co">#   unnest_wider(geometry)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>That gives us new <code>bounds</code> (a rectangular region) and <code>location</code> (a point). We can unnest <code>location</code> to see the latitude (<code>lat</code>) and longitude (<code>lng</code>):</p>
<div class="cell">
<div class="sourceCode" id="cb50"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># locations |&gt; </span></span>
<span><span class="co">#   select(city, formatted_address, geometry) |&gt; </span></span>
<span><span class="co">#   unnest_wider(geometry) |&gt; </span></span>
<span><span class="co">#   unnest_wider(location)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Extracting the bounds requires a few more steps</p>
<div class="cell">
<div class="sourceCode" id="cb51"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># locations |&gt; </span></span>
<span><span class="co">#   select(city, formatted_address, geometry) |&gt; </span></span>
<span><span class="co">#   unnest_wider(geometry) |&gt; </span></span>
<span><span class="co">#   # focus on the variables of interest</span></span>
<span><span class="co">#   select(!location:viewport) |&gt;</span></span>
<span><span class="co">#   unnest_wider(bounds)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>We then rename <code>southwest</code> and <code>northeast</code> (the corners of the rectangle) so we can use <code>names_sep</code> to create short but evocative names:</p>
</section></section><section id="r-locations-selectcity-formatted_address-geometry-unnest_widergeometry-selectlocationviewport-unnest_widerbounds-renamene-northeast-sw-southwest-unnest_widercne-sw-names_sep-_" class="level1" data-number="26"><h1 data-number="26">
<span class="header-section-number">26</span> <code>{r} # locations |&gt;  #   select(city, formatted_address, geometry) |&gt;  #   unnest_wider(geometry) |&gt;  #   select(!location:viewport) |&gt; #   unnest_wider(bounds) |&gt;  #   rename(ne = northeast, sw = southwest) |&gt;  #   unnest_wider(c(ne, sw), names_sep = "_")</code>
</h1>
<p>Note how we unnest two columns simultaneously by supplying a vector of variable names to <code><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_wider()</a></code>.</p>
<p>This somewhere that <code><a href="https://tidyr.tidyverse.org/reference/hoist.html">hoist()</a></code>, mentioned briefly above, can be useful. Once you’ve discovered the path to get to the components you’re interested in, you can extract them directly using <code><a href="https://tidyr.tidyverse.org/reference/hoist.html">hoist()</a></code>:</p>
<div class="cell">
<div class="sourceCode" id="cb52"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># &lt;!-- locations |&gt;  --&gt;</span></span>
<span><span class="co"># &lt;!--   select(city, formatted_address, geometry) |&gt;  --&gt;</span></span>
<span><span class="co"># &lt;!--   hoist( --&gt;</span></span>
<span><span class="co"># &lt;!--     geometry, --&gt;</span></span>
<span><span class="co"># &lt;!--     ne_lat = c("bounds", "northeast", "lat"), --&gt;</span></span>
<span><span class="co"># &lt;!--     sw_lat = c("bounds", "southwest", "lat"), --&gt;</span></span>
<span><span class="co"># &lt;!--     ne_lng = c("bounds", "northeast", "lng"), --&gt;</span></span>
<span><span class="co"># &lt;!--     sw_lng = c("bounds", "southwest", "lng"), --&gt;</span></span>
<span><span class="co"># &lt;!--   ) --&gt;</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>If these case studies have whetted your appetite for more real-life rectangling, you can see a few more examples in <code>vignette("rectangling", package = "tidyr")</code>.</p>
<section id="exercises-1" class="level3" data-number="26.0.1"><h3 data-number="26.0.1" class="anchored" data-anchor-id="exercises-1">
<span class="header-section-number">26.0.1</span> Exercises</h3>
<ol type="1">
<li><p>Roughly estimate when <code>gh_repos</code> was created. Why can you only roughly estimate the date?</p></li>
<li><p>The <code>owner</code> column of <code>gh_repo</code> contains a lot of duplicated information because each owner can have many repos. Can you construct a <code>owners</code> data frame that contains one row for each owner? (Hint: does <code><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct()</a></code> work with <code>list-cols</code>?)</p></li>
<li>
<p>Explain the following code line-by-line. Why is it interesting? Why does it work for <code>got_chars</code> but might not work in general?</p>
<div class="cell">
<div class="sourceCode" id="cb53"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>json <span class="op">=</span> <span class="va">got_chars</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_wider</a></span><span class="op">(</span><span class="va">json</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">id</span>, <span class="fu">where</span><span class="op">(</span><span class="va">is.list</span><span class="op">)</span><span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/pivot_longer.html">pivot_longer</a></span><span class="op">(</span></span>
<span>    <span class="fu">where</span><span class="op">(</span><span class="va">is.list</span><span class="op">)</span>, </span>
<span>    names_to <span class="op">=</span> <span class="st">"name"</span>, </span>
<span>    values_to <span class="op">=</span> <span class="st">"value"</span></span>
<span>  <span class="op">)</span> <span class="op"><a href="https://magrittr.tidyverse.org/reference/pipe.html">%&gt;%</a></span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer</a></span><span class="op">(</span><span class="va">value</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 486 × 3</span></span>
<span><span class="co">#&gt;      id name    value                                               </span></span>
<span><span class="co">#&gt;   &lt;int&gt; &lt;chr&gt;   &lt;chr&gt;                                               </span></span>
<span><span class="co">#&gt; 1  1022 titles  Prince of Winterfell                                </span></span>
<span><span class="co">#&gt; 2  1022 titles  Captain of Sea Bitch                                </span></span>
<span><span class="co">#&gt; 3  1022 titles  Lord of the Iron Islands (by law of the green lands)</span></span>
<span><span class="co">#&gt; 4  1022 aliases Prince of Fools                                     </span></span>
<span><span class="co">#&gt; 5  1022 aliases Theon Turncloak                                     </span></span>
<span><span class="co">#&gt; 6  1022 aliases Reek                                                </span></span>
<span><span class="co">#&gt; # … with 480 more rows</span></span>
<span><span class="co">#&gt; # ℹ Use `print(n = ...)` to see more rows</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</li>
<li><p>In <code>gmaps_cities</code>, what does <code>address_components</code> contain? Why does the length vary between rows? Unnest it appropriately to figure it out. (Hint: <code>types</code> always appears to contain two elements. Does <code><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_wider()</a></code> make it easier to work with than <code><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer()</a></code>?) .</p></li>
</ol></section><section id="json" class="level2" data-number="26.1"><h2 data-number="26.1" class="anchored" data-anchor-id="json">
<span class="header-section-number">26.1</span> JSON</h2>
<p>All of the case studies in the previous section were sourced from wild-caught JSON files. JSON is short for <strong>j</strong>ava<strong>s</strong>cript <strong>o</strong>bject <strong>n</strong>otation and is the way that most web APIs return data. It’s important to understand it because while JSON and R’s data types are pretty similar, there isn’t a perfect 1-to-1 mapping, so it’s good to understand a bit about JSON if things go wrong.</p>
<section id="data-types" class="level3" data-number="26.1.1"><h3 data-number="26.1.1" class="anchored" data-anchor-id="data-types">
<span class="header-section-number">26.1.1</span> Data types</h3>
<p>JSON is a simple format designed to be easily read and written by machines, not humans. It has six key data types. Four of them are scalars:</p>
<ul>
<li>The simplest type is a null, which is written <code>null</code>, which plays the same role as both <code>NULL</code> and <code>NA</code> in R. It represents the absence of data.</li>
<li>A <strong>string</strong> is much like a string in R, but must use double quotes, not single quotes.</li>
<li>A <strong>number</strong> is similar to R’s numbers: they can be use integer (e.g.&nbsp;123), decimal (e.g.&nbsp;123.45), or scientific (e.g.&nbsp;1.23e3) notation. JSON doesn’t support Inf, -Inf, or NaN.</li>
<li>A <strong>boolean</strong> is similar to R’s <code>TRUE</code> and <code>FALSE</code>, but use lower case <code>true</code> and <code>false</code>.</li>
</ul>
<p>JSON’s strings, numbers, and booleans are pretty similar to R’s character, numeric, and logical vectors. The main difference is that JSON’s scalars can only represent a single value. To represent multiple values you need to use one of the two remaining two types, arrays and objects.</p>
<p>Both arrays and objects are similar to lists in R; the difference is whether or not they’re named. An <strong>array</strong> is like an unnamed list, and is written with <code>[]</code>. For example <code>[1, 2, 3]</code> is an array containing 3 numbers, and <code>[null, 1, "string", false]</code> is an array that contains a null, a number, a string, and a boolean. An <strong>object</strong> is like a named list, and they’re written with <code><a href="https://rdrr.io/r/base/Paren.html">{}</a></code>. For example, <code>{"x": 1, "y": 2}</code> is an object that maps <code>x</code> to 1 and <code>y</code> to 2.</p>
</section><section id="jsonlite" class="level3" data-number="26.1.2"><h3 data-number="26.1.2" class="anchored" data-anchor-id="jsonlite">
<span class="header-section-number">26.1.2</span> jsonlite</h3>
<p>To convert JSON into R data structures, we recommend that you use the jsonlite package, by Jeroen Oooms. We’ll use only two jsonlite functions: <code><a href="https://rdrr.io/pkg/jsonlite/man/read_json.html">read_json()</a></code> and <code><a href="https://rdrr.io/pkg/jsonlite/man/read_json.html">parse_json()</a></code>. In real life, you’ll use <code><a href="https://rdrr.io/pkg/jsonlite/man/read_json.html">read_json()</a></code> to read a JSON file from disk. For example, we the repurrsive package also provides the source for <code>gh_user</code> as a JSON file:</p>
<div class="cell">
<div class="sourceCode" id="cb54"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># A path to a json file inside the package:</span></span>
<span><span class="fu"><a href="https://rdrr.io/pkg/repurrrsive/man/gh_users_json.html">gh_users_json</a></span><span class="op">(</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] "C:/Users/billy/AppData/Local/R/win-library/4.2/repurrrsive/extdata/gh_users.json"</span></span>
<span></span>
<span><span class="co"># Read it with read_json()</span></span>
<span><span class="va">gh_users2</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/jsonlite/man/read_json.html">read_json</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/repurrrsive/man/gh_users_json.html">gh_users_json</a></span><span class="op">(</span><span class="op">)</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># Check it's the same as the data we were using previously</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/base/identical.html">identical</a></span><span class="op">(</span><span class="va">gh_users</span>, <span class="va">gh_users2</span><span class="op">)</span></span>
<span><span class="co">#&gt; [1] TRUE</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In this book, I’ll also use <code><a href="https://rdrr.io/pkg/jsonlite/man/read_json.html">parse_json()</a></code>, since it takes a string containing JSON, which makes it good for generating simple examples. To get started, here’s three simple JSON datasets, starting with a number, then putting a few number in an array, then putting that array in an object:</p>
<div class="cell">
<div class="sourceCode" id="cb55"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/jsonlite/man/read_json.html">parse_json</a></span><span class="op">(</span><span class="st">'1'</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt;  int 1</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/jsonlite/man/read_json.html">parse_json</a></span><span class="op">(</span><span class="st">'[1, 2, 3]'</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; List of 3</span></span>
<span><span class="co">#&gt;  $ : int 1</span></span>
<span><span class="co">#&gt;  $ : int 2</span></span>
<span><span class="co">#&gt;  $ : int 3</span></span>
<span><span class="fu"><a href="https://rdrr.io/r/utils/str.html">str</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/jsonlite/man/read_json.html">parse_json</a></span><span class="op">(</span><span class="st">'{"x": [1, 2, 3]}'</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="co">#&gt; List of 1</span></span>
<span><span class="co">#&gt;  $ x:List of 3</span></span>
<span><span class="co">#&gt;   ..$ : int 1</span></span>
<span><span class="co">#&gt;   ..$ : int 2</span></span>
<span><span class="co">#&gt;   ..$ : int 3</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>jsonlite has another important function called <code><a href="https://rdrr.io/pkg/jsonlite/man/fromJSON.html">fromJSON()</a></code>. We don’t use it here because it performs automatic simplification (<code>simplifyVector = TRUE)</code>. This often works well, particularly in simple cases, but we think you’re better off doing the rectangling yourself so you know exactly what’s happening and can more easily handle the most complicated nested structures.</p>
</section><section id="starting-the-rectangling-process" class="level3" data-number="26.1.3"><h3 data-number="26.1.3" class="anchored" data-anchor-id="starting-the-rectangling-process">
<span class="header-section-number">26.1.3</span> Starting the rectangling process</h3>
<p>In most cases, JSON files contain a single top-level array, because they’re designed to provide data about multiple “things”, e.g.&nbsp;multiple pages, or multiple records, or multiple results. In this case, you’ll start your rectangling with <code>tibble(json)</code> so that each element becomes a row:</p>
<div class="cell">
<div class="sourceCode" id="cb56"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">json</span> <span class="op">&lt;-</span> <span class="st">'[</span></span>
<span><span class="st">  {"name": "John", "age": 34},</span></span>
<span><span class="st">  {"name": "Susan", "age": 27}</span></span>
<span><span class="st">]'</span></span>
<span><span class="va">df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>json <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/jsonlite/man/read_json.html">parse_json</a></span><span class="op">(</span><span class="va">json</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">df</span></span>
<span><span class="co">#&gt; # A tibble: 2 × 1</span></span>
<span><span class="co">#&gt;   json            </span></span>
<span><span class="co">#&gt;   &lt;list&gt;          </span></span>
<span><span class="co">#&gt; 1 &lt;named list [2]&gt;</span></span>
<span><span class="co">#&gt; 2 &lt;named list [2]&gt;</span></span>
<span><span class="va">df</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_wider</a></span><span class="op">(</span><span class="va">json</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 2 × 2</span></span>
<span><span class="co">#&gt;   name    age</span></span>
<span><span class="co">#&gt;   &lt;chr&gt; &lt;int&gt;</span></span>
<span><span class="co">#&gt; 1 John     34</span></span>
<span><span class="co">#&gt; 2 Susan    27</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>In rarer cases, the JSON consists of a single top-level JSON object, representing one “thing”. In this case, you’ll need to kick off the rectangling process by wrapping it a list, before you put it in a tibble.</p>
<div class="cell">
<div class="sourceCode" id="cb57"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">json</span> <span class="op">&lt;-</span> <span class="st">'{</span></span>
<span><span class="st">  "status": "OK", </span></span>
<span><span class="st">  "results": [</span></span>
<span><span class="st">    {"name": "John", "age": 34},</span></span>
<span><span class="st">    {"name": "Susan", "age": 27}</span></span>
<span><span class="st"> ]</span></span>
<span><span class="st">}</span></span>
<span><span class="st">'</span></span>
<span><span class="va">df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>json <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/pkg/jsonlite/man/read_json.html">parse_json</a></span><span class="op">(</span><span class="va">json</span><span class="op">)</span><span class="op">)</span><span class="op">)</span></span>
<span><span class="va">df</span></span>
<span><span class="co">#&gt; # A tibble: 1 × 1</span></span>
<span><span class="co">#&gt;   json            </span></span>
<span><span class="co">#&gt;   &lt;list&gt;          </span></span>
<span><span class="co">#&gt; 1 &lt;named list [2]&gt;</span></span>
<span><span class="va">df</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_wider</a></span><span class="op">(</span><span class="va">json</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_longer</a></span><span class="op">(</span><span class="va">results</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_wider</a></span><span class="op">(</span><span class="va">results</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 2 × 3</span></span>
<span><span class="co">#&gt;   status name    age</span></span>
<span><span class="co">#&gt;   &lt;chr&gt;  &lt;chr&gt; &lt;int&gt;</span></span>
<span><span class="co">#&gt; 1 OK     John     34</span></span>
<span><span class="co">#&gt; 2 OK     Susan    27</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Alternatively, you can reach inside the parsed JSON and start with the bit that you actually care about:</p>
<div class="cell">
<div class="sourceCode" id="cb58"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">df</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>results <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/pkg/jsonlite/man/read_json.html">parse_json</a></span><span class="op">(</span><span class="va">json</span><span class="op">)</span><span class="op">$</span><span class="va">results</span><span class="op">)</span></span>
<span><span class="va">df</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://tidyr.tidyverse.org/reference/hoist.html">unnest_wider</a></span><span class="op">(</span><span class="va">results</span><span class="op">)</span></span>
<span><span class="co">#&gt; # A tibble: 2 × 2</span></span>
<span><span class="co">#&gt;   name    age</span></span>
<span><span class="co">#&gt;   &lt;chr&gt; &lt;int&gt;</span></span>
<span><span class="co">#&gt; 1 John     34</span></span>
<span><span class="co">#&gt; 2 Susan    27</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section><section id="translation-challenges" class="level3" data-number="26.1.4"><h3 data-number="26.1.4" class="anchored" data-anchor-id="translation-challenges">
<span class="header-section-number">26.1.4</span> Translation challenges</h3>
<p>Since JSON doesn’t have any way to represent dates or date-times, they’re often stored as ISO8601 date times in strings, and you’ll need to use <code><a href="https://readr.tidyverse.org/reference/parse_datetime.html">readr::parse_date()</a></code> or <code><a href="https://readr.tidyverse.org/reference/parse_datetime.html">readr::parse_datetime()</a></code> to turn them into the correct data structure. Similarly, JSON’s rules for representing floating point numbers in JSON are a little imprecise, so you’ll also sometimes find numbers stored in strings. Apply <code><a href="https://readr.tidyverse.org/reference/parse_atomic.html">readr::parse_double()</a></code> as needed to the get correct variable type.</p>
</section><section id="exercises-2" class="level3" data-number="26.1.5"><h3 data-number="26.1.5" class="anchored" data-anchor-id="exercises-2">
<span class="header-section-number">26.1.5</span> Exercises</h3>
<ol type="1">
<li>
<p>Rectangle the <code>df_col</code> and <code>df_row</code> below. They represent the two ways of encoding a data frame in JSON.</p>
<div class="cell">
<div class="sourceCode" id="cb59"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">json_col</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/jsonlite/man/read_json.html">parse_json</a></span><span class="op">(</span><span class="st">'</span></span>
<span><span class="st">  {</span></span>
<span><span class="st">    "x": ["a", "x", "z"],</span></span>
<span><span class="st">    "y": [10, null, 3]</span></span>
<span><span class="st">  }</span></span>
<span><span class="st">'</span><span class="op">)</span></span>
<span><span class="va">json_row</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/jsonlite/man/read_json.html">parse_json</a></span><span class="op">(</span><span class="st">'</span></span>
<span><span class="st">  [</span></span>
<span><span class="st">    {"x": "a", "y": 10},</span></span>
<span><span class="st">    {"x": "x", "y": null},</span></span>
<span><span class="st">    {"x": "z", "y": 3}</span></span>
<span><span class="st">  ]</span></span>
<span><span class="st">'</span><span class="op">)</span></span>
<span></span>
<span><span class="va">df_col</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>json <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span><span class="va">json_col</span><span class="op">)</span><span class="op">)</span> </span>
<span><span class="va">df_row</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://tibble.tidyverse.org/reference/tibble.html">tibble</a></span><span class="op">(</span>json <span class="op">=</span> <span class="va">json_row</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</li>
</ol>


</section></section></section><section class="footnotes footnotes-end-of-document" role="doc-endnotes"><hr>
<ol>
<li id="fn1" role="doc-endnote"><p>This is an RStudio feature.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol></section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      let href = ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./databases.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">24</span>&nbsp; <span class="chapter-title">Databases</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./webscraping.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">26</span>&nbsp; <span class="chapter-title">Web scraping</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer"><div class="nav-footer">
    <div class="nav-footer-left">R for Data Science (2e) was written by Hadley Wickham, Mine Çetinkaya-Rundel, and Garrett Grolemund.</div>   
    <div class="nav-footer-right">This book was built with <a href="https://quarto.org/">Quarto</a>.</div>
  </div>
</footer>


</body></html>